# Understanding how to use Batch dataset to train Models

- Lets use batch in our iris dataset

In [1]:
from sklearn.datasets import load_iris

In [2]:
data = load_iris()

In [3]:
X = data["data"]
y = data["target"]

In [4]:
X.shape, y.shape

((150, 4), (150,))

In [5]:
X

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

In [6]:
y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [7]:
from sklearn.model_selection import train_test_split

In [8]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 42)
X_train.shape, X_test.shape, y_train.shape, y_test.shape

((120, 4), (30, 4), (120,), (30,))

In [9]:
import torch
from torch.utils.data import TensorDataset, DataLoader

In [10]:
# Convert train numpy data into tensors
X_train_tensors = torch.tensor(X_train, dtype=torch.float)
y_train_tensors = torch.tensor(y_train, dtype=torch.long)

In [11]:
# convert test numpy data into tensors
X_test_tensors = torch.tensor(X_test, dtype=torch.float)
y_test_tensors = torch.tensor(y_test, dtype=torch.long)

In [12]:
# now lets convert into tensor dataset

train_dataset = TensorDataset(X_train_tensors, y_train_tensors)
test_dataset = TensorDataset(X_test_tensors, y_test_tensors)

In [13]:
list(train_dataset)[:5]

[(tensor([4.6000, 3.6000, 1.0000, 0.2000]), tensor(0)),
 (tensor([5.7000, 4.4000, 1.5000, 0.4000]), tensor(0)),
 (tensor([6.7000, 3.1000, 4.4000, 1.4000]), tensor(1)),
 (tensor([4.8000, 3.4000, 1.6000, 0.2000]), tensor(0)),
 (tensor([4.4000, 3.2000, 1.3000, 0.2000]), tensor(0))]

In [14]:
list(test_dataset)

[(tensor([6.1000, 2.8000, 4.7000, 1.2000]), tensor(1)),
 (tensor([5.7000, 3.8000, 1.7000, 0.3000]), tensor(0)),
 (tensor([7.7000, 2.6000, 6.9000, 2.3000]), tensor(2)),
 (tensor([6.0000, 2.9000, 4.5000, 1.5000]), tensor(1)),
 (tensor([6.8000, 2.8000, 4.8000, 1.4000]), tensor(1)),
 (tensor([5.4000, 3.4000, 1.5000, 0.4000]), tensor(0)),
 (tensor([5.6000, 2.9000, 3.6000, 1.3000]), tensor(1)),
 (tensor([6.9000, 3.1000, 5.1000, 2.3000]), tensor(2)),
 (tensor([6.2000, 2.2000, 4.5000, 1.5000]), tensor(1)),
 (tensor([5.8000, 2.7000, 3.9000, 1.2000]), tensor(1)),
 (tensor([6.5000, 3.2000, 5.1000, 2.0000]), tensor(2)),
 (tensor([4.8000, 3.0000, 1.4000, 0.1000]), tensor(0)),
 (tensor([5.5000, 3.5000, 1.3000, 0.2000]), tensor(0)),
 (tensor([4.9000, 3.1000, 1.5000, 0.1000]), tensor(0)),
 (tensor([5.1000, 3.8000, 1.5000, 0.3000]), tensor(0)),
 (tensor([6.3000, 3.3000, 4.7000, 1.6000]), tensor(1)),
 (tensor([6.5000, 3.0000, 5.8000, 2.2000]), tensor(2)),
 (tensor([5.6000, 2.5000, 3.9000, 1.1000]), tens

In [15]:
# now lets convert our data into batches

train_loader = DataLoader(train_dataset, batch_size=16, shuffle=True)
test_loader = DataLoader(test_dataset, batch_size=2, shuffle=True)

In [16]:
list(train_loader)

[[tensor([[6.2000, 2.9000, 4.3000, 1.3000],
          [6.7000, 3.3000, 5.7000, 2.5000],
          [6.5000, 3.0000, 5.5000, 1.8000],
          [5.1000, 3.8000, 1.9000, 0.4000],
          [6.8000, 3.0000, 5.5000, 2.1000],
          [6.7000, 3.1000, 5.6000, 2.4000],
          [5.0000, 2.3000, 3.3000, 1.0000],
          [7.7000, 2.8000, 6.7000, 2.0000],
          [6.2000, 2.8000, 4.8000, 1.8000],
          [5.4000, 3.7000, 1.5000, 0.2000],
          [6.1000, 2.6000, 5.6000, 1.4000],
          [6.4000, 3.1000, 5.5000, 1.8000],
          [5.5000, 2.6000, 4.4000, 1.2000],
          [6.1000, 3.0000, 4.6000, 1.4000],
          [4.3000, 3.0000, 1.1000, 0.1000],
          [5.1000, 2.5000, 3.0000, 1.1000]]),
  tensor([1, 2, 2, 0, 2, 2, 1, 2, 2, 0, 2, 2, 1, 1, 0, 1])],
 [tensor([[6.4000, 2.7000, 5.3000, 1.9000],
          [5.7000, 2.8000, 4.1000, 1.3000],
          [4.8000, 3.4000, 1.6000, 0.2000],
          [5.8000, 4.0000, 1.2000, 0.2000],
          [5.5000, 2.4000, 3.8000, 1.1000],
          [4.

# Model

In [17]:
import torch.nn as nn

In [18]:
class Model(nn.Module):
    def __init__(self):
        super(Model, self).__init__()

        # layers
        self.fc1 = nn.Linear(4, 8) # input layer
        self.fc2 = nn.Linear(8, 16) # hidden layer
        self.fc3 = nn.Linear(16, 8) # hidden layer
        self.fc4 = nn.Linear(8, 3) # output layer

    def forward(self, x):
        x = self.fc1(x)
        x = self.fc2(x)
        x = self.fc3(x)
        x  = self.fc4(x)

        return x

In [19]:
model = Model()
model

Model(
  (fc1): Linear(in_features=4, out_features=8, bias=True)
  (fc2): Linear(in_features=8, out_features=16, bias=True)
  (fc3): Linear(in_features=16, out_features=8, bias=True)
  (fc4): Linear(in_features=8, out_features=3, bias=True)
)

In [20]:
loss_function = nn.CrossEntropyLoss()
optimizer = torch.optim.Adam(model.parameters(), lr=0.001)

In [21]:
from sklearn.metrics import accuracy_score

In [22]:
epoches = 500

for batch_X, batch_y in train_loader:
    for epoch in range(epoches):
        model.train()

        out = model(batch_X)
        loss = loss_function(out, batch_y)

        optimizer.zero_grad()
        loss.backward()
        optimizer.step()

        # calculate accuracy
        model.eval()
        y_pred = model(X_test_tensors).argmax(dim=1)
        acc = accuracy_score(y_test_tensors, y_pred)

        if epoch % 10 == 0:
            print("Epoch: ", epoch, "Loss: ", loss.item(), "Accuracy: ", acc)

Epoch:  0 Loss:  1.3401615619659424 Accuracy:  0.6333333333333333
Epoch:  10 Loss:  1.0772361755371094 Accuracy:  0.6333333333333333
Epoch:  20 Loss:  0.9791727662086487 Accuracy:  0.2
Epoch:  30 Loss:  0.9513835906982422 Accuracy:  0.3
Epoch:  40 Loss:  0.9177685379981995 Accuracy:  0.5333333333333333
Epoch:  50 Loss:  0.8796913027763367 Accuracy:  0.6333333333333333
Epoch:  60 Loss:  0.8387916684150696 Accuracy:  0.6333333333333333
Epoch:  70 Loss:  0.7910186052322388 Accuracy:  0.6333333333333333
Epoch:  80 Loss:  0.7371116876602173 Accuracy:  0.6333333333333333
Epoch:  90 Loss:  0.6795592904090881 Accuracy:  0.6333333333333333
Epoch:  100 Loss:  0.622769832611084 Accuracy:  0.8333333333333334
Epoch:  110 Loss:  0.571118950843811 Accuracy:  0.9
Epoch:  120 Loss:  0.5267524719238281 Accuracy:  0.9666666666666667
Epoch:  130 Loss:  0.48879438638687134 Accuracy:  0.9333333333333333
Epoch:  140 Loss:  0.45472100377082825 Accuracy:  0.9666666666666667
Epoch:  150 Loss:  0.422048449516296

In [23]:
model.eval()
y_pred = model(X_test_tensors).argmax(dim=1)
accuracy_score(y_test_tensors, y_pred)

0.8666666666666667

# Working with crop recommendation dataset

In [24]:
import pandas as pd

In [25]:
data = pd.read_csv("Datasets/Crop_recommendation.csv")

In [26]:
data.columns

Index(['N', 'P', 'K', 'temperature', 'humidity', 'ph', 'rainfall', 'label'], dtype='str')

In [27]:
data.head()

,N,P,K,temperature,humidity,ph,rainfall,label
0,90,42,43,20.879744,82.002744,6.502985,202.935536,rice
1,85,58,41,21.770462,80.319644,7.038096,226.655537,rice
2,60,55,44,23.004459,82.320763,7.840207,263.964248,rice
3,74,35,40,26.491096,80.158363,6.980401,242.864034,rice
4,78,42,42,20.130175,81.604873,7.628473,262.717340,rice


In [28]:
data.info()

<class 'pandas.DataFrame'>
RangeIndex: 2200 entries, 0 to 2199
Data columns (total 8 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   N            2200 non-null   int64  
 1   P            2200 non-null   int64  
 2   K            2200 non-null   int64  
 3   temperature  2200 non-null   float64
 4   humidity     2200 non-null   float64
 5   ph           2200 non-null   float64
 6   rainfall     2200 non-null   float64
 7   label        2200 non-null   str    
dtypes: float64(4), int64(3), str(1)
memory usage: 137.6 KB


In [29]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()

In [30]:
X = data.drop(["label"], axis=1)
y = data["label"]

label_names = list(set(data.label))

In [31]:
label_names

['pigeonpeas',
 'rice',
 'watermelon',
 'coconut',
 'mungbean',
 'grapes',
 'kidneybeans',
 'mothbeans',
 'pomegranate',
 'cotton',
 'maize',
 'papaya',
 'mango',
 'banana',
 'apple',
 'muskmelon',
 'jute',
 'blackgram',
 'orange',
 'coffee',
 'chickpea',
 'lentil']

In [32]:
y = le.fit_transform(y)
y

array([20, 20, 20, ...,  5,  5,  5], shape=(2200,))

- Lets convert our data into tensors

In [33]:
import torch

In [34]:
X.values[:5]

array([[ 90.        ,  42.        ,  43.        ,  20.87974371,
         82.00274423,   6.50298529, 202.9355362 ],
       [ 85.        ,  58.        ,  41.        ,  21.77046169,
         80.31964408,   7.03809636, 226.6555374 ],
       [ 60.        ,  55.        ,  44.        ,  23.00445915,
         82.3207629 ,   7.84020714, 263.9642476 ],
       [ 74.        ,  35.        ,  40.        ,  26.49109635,
         80.15836264,   6.9804009 , 242.8640342 ],
       [ 78.        ,  42.        ,  42.        ,  20.13017482,
         81.60487287,   7.62847289, 262.7173405 ]])

In [35]:
X = torch.tensor(X.values, dtype=torch.float)
y = torch.tensor(y, dtype=torch.long)

- now let's split our data  

In [36]:
from sklearn.model_selection import train_test_split


In [37]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 42)
X_train.shape, X_test.shape, y_train.shape, y_test.shape

(torch.Size([1760, 7]),
 torch.Size([440, 7]),
 torch.Size([1760]),
 torch.Size([440]))

- now let's convert our data into batch

In [38]:
from torch.utils.data import TensorDataset, DataLoader

In [39]:
train_dataset = TensorDataset(X_train, y_train)
test_dataset = TensorDataset(X_test, y_test)

In [40]:
train_batch = DataLoader(train_dataset, batch_size=32, shuffle=True)

In [41]:
list(train_batch)

[[tensor([[ 21.0000,  39.0000,  20.0000,  27.0618,  52.3003,   7.3880,  60.7458],
          [ 28.0000,  10.0000,  30.0000,  29.8691,  91.1472,   6.3057, 192.7679],
          [ 86.0000,  55.0000,  21.0000,  21.5416,  59.6402,   6.8039, 109.7515],
          [ 83.0000,  10.0000,  53.0000,  24.9299,  85.0080,   6.1951,  48.7586],
          [ 33.0000,  23.0000,  45.0000,  20.0022,  85.8362,   7.1165, 112.3370],
          [ 55.0000,  77.0000,  22.0000,  31.4345,  62.9930,   7.7606,  64.7765],
          [111.0000,   5.0000,  50.0000,  27.5935,  91.7974,   6.3999,  24.8427],
          [ 61.0000,  41.0000,  17.0000,  25.1421,  65.2618,   6.0219,  76.6846],
          [ 70.0000,  50.0000,  53.0000,  37.4621,  90.4497,   6.9338, 172.3458],
          [ 30.0000,  17.0000,  31.0000,  31.2048,  54.4996,   6.8044,  94.6295],
          [107.0000,  12.0000,  46.0000,  29.5724,  93.6187,   6.5598,  27.5692],
          [ 82.0000,  35.0000,  44.0000,  26.9666,  78.2105,   6.2390, 169.8391],
          [ 25.0

In [42]:
import torch.nn as nn

In [43]:
class CropModel(nn.Module):
    def __init__(self):
        super(CropModel, self).__init__()

        self.fc1 = nn.Linear(7, 14)
        self.relu1 = nn.ReLU()

        self.fc2 = nn.Linear(14, 32)
        self.relu2 = nn.ReLU()

        self.fc3 = nn.Linear(32, 22)
        
    def forward(self, x):
        x = self.fc1(x)
        x = self.relu1(x)

        x = self.fc2(x)
        x = self.relu2(x)

        x = self.fc3(x)
        
        return x

In [44]:
model = CropModel()

In [45]:
model

CropModel(
  (fc1): Linear(in_features=7, out_features=14, bias=True)
  (relu1): ReLU()
  (fc2): Linear(in_features=14, out_features=32, bias=True)
  (relu2): ReLU()
  (fc3): Linear(in_features=32, out_features=22, bias=True)
)

In [46]:
loss_function = nn.CrossEntropyLoss()
optimizer = torch.optim.Adam(model.parameters(), lr=0.001)

In [47]:
from sklearn.metrics import accuracy_score

In [48]:
epoches = 500

for batch_X, batch_y in train_batch:
    for epoch in range(epoches):
        model.train()

        out = model(batch_X)
        loss = loss_function(out, batch_y)

        optimizer.zero_grad()
        loss.backward()
        optimizer.step()

        # accuracy
        y_pred = model(X_test).argmax(dim=1)
        acc = accuracy_score(y_test, y_pred)

        if epoch % 10 == 0:
            print("Epoch: ", epoch, " Loss: ", loss.item(), " Accuracy: ", acc)

Epoch:  0  Loss:  6.0024919509887695  Accuracy:  0.06136363636363636
Epoch:  10  Loss:  3.5150575637817383  Accuracy:  0.18409090909090908
Epoch:  20  Loss:  2.301872491836548  Accuracy:  0.2681818181818182
Epoch:  30  Loss:  1.6352201700210571  Accuracy:  0.32045454545454544
Epoch:  40  Loss:  1.2075369358062744  Accuracy:  0.37727272727272726
Epoch:  50  Loss:  0.9135417938232422  Accuracy:  0.4636363636363636
Epoch:  60  Loss:  0.7016558051109314  Accuracy:  0.5113636363636364
Epoch:  70  Loss:  0.5421968102455139  Accuracy:  0.5659090909090909
Epoch:  80  Loss:  0.42544978857040405  Accuracy:  0.5909090909090909
Epoch:  90  Loss:  0.33586227893829346  Accuracy:  0.6045454545454545
Epoch:  100  Loss:  0.2704908847808838  Accuracy:  0.625
Epoch:  110  Loss:  0.22130291163921356  Accuracy:  0.6363636363636364
Epoch:  120  Loss:  0.18323566019535065  Accuracy:  0.6454545454545455
Epoch:  130  Loss:  0.15334175527095795  Accuracy:  0.6659090909090909
Epoch:  140  Loss:  0.12940190732479

- evaluate model

In [49]:
model.eval()

y_pred = model(X_test).argmax(dim=1)
accuracy_score(y_test, y_pred)


0.7636363636363637

In [50]:
from sklearn.metrics import classification_report, confusion_matrix

In [51]:
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.92      1.00      0.96        23
           1       0.88      1.00      0.93        21
           2       0.52      0.80      0.63        20
           3       0.81      1.00      0.90        26
           4       1.00      0.89      0.94        27
           5       0.93      0.76      0.84        17
           6       0.82      0.82      0.82        17
           7       1.00      0.86      0.92        14
           8       0.49      0.74      0.59        23
           9       0.56      1.00      0.71        20
          10       0.34      1.00      0.51        11
          11       0.83      0.71      0.77        21
          12       1.00      0.68      0.81        19
          13       0.54      0.29      0.38        24
          14       1.00      0.47      0.64        19
          15       1.00      1.00      1.00        17
          16       1.00      1.00      1.00        14
          17       0.81    

/home/aishwarya/Downloads/Notes/PyTorch_Notes/Notebooks/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1833: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/home/aishwarya/Downloads/Notes/PyTorch_Notes/Notebooks/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1833: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/home/aishwarya/Downloads/Notes/PyTorch_Notes/Notebooks/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1833: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_divisio

- Using wandb to visualize performance.

In [52]:
model = CropModel()
optimizer = torch.optim.Adam(model.parameters(), lr=0.001)

In [53]:
import wandb
from sklearn.metrics import accuracy_score

def init_wandb(batch_size):
    # Returning the run object so its accessible
    return wandb.init(
        entity="aishwaryapatil845-aish-com",
        project="Crop_Recommendation_New_Model",
        name=f"Model-BS-{batch_size}",
        config={
            "learning_rate": 0.001,
            "architecture": "FNN",
            "dataset": "crop_recommendation",
            "epochs": 501,
        }
    )

# Initialize the run 
run = init_wandb(batch_size=32)
epochs = 501

for epoch in range(epochs):
    model.train()
    total_loss = 0

    for batch_X, batch_y in train_batch:
        # Standard Training Step
        out = model(batch_X)
        loss = loss_function(out, batch_y)

        optimizer.zero_grad()
        loss.backward()
        optimizer.step()

        total_loss += loss.item()

        # Evaluation
        model.eval()
        with torch.no_grad():
            y_pred = model(X_test).argmax(dim=1)
            acc = accuracy_score(y_test.cpu(), y_pred.cpu())

            # Log metrics once per epoch
        avg_loss = total_loss / len(train_batch)
        if epoch % 10 == 0:
            print(f"Epoch: {epoch} | Loss: {avg_loss:.4f} | Accuracy: {acc:.4f}")
            run.log({"loss": avg_loss, "accuracy": acc, "epoch": epoch})
            
#Close the W&B run
run.finish()


wandb: ERROR Failed to detect the name of this notebook. You can set it manually with the WANDB_NOTEBOOK_NAME environment variable to enable code saving.
wandb: [wandb.login()] Loaded credentials for https://api.wandb.ai from /home/aishwarya/.netrc.
wandb: Currently logged in as: aishwaryapatil845 (aishwaryapatil845-aish-com) to https://api.wandb.ai. Use `wandb login --relogin` to force relogin


Epoch: 0 | Loss: 0.3650 | Accuracy: 0.0432
Epoch: 0 | Loss: 0.5912 | Accuracy: 0.0432
Epoch: 0 | Loss: 0.7917 | Accuracy: 0.0432
Epoch: 0 | Loss: 1.0513 | Accuracy: 0.0409
Epoch: 0 | Loss: 1.2638 | Accuracy: 0.0295
Epoch: 0 | Loss: 1.5396 | Accuracy: 0.0250
Epoch: 0 | Loss: 1.7408 | Accuracy: 0.0205
Epoch: 0 | Loss: 1.9596 | Accuracy: 0.0091
Epoch: 0 | Loss: 2.1119 | Accuracy: 0.0045
Epoch: 0 | Loss: 2.3149 | Accuracy: 0.0023
Epoch: 0 | Loss: 2.4691 | Accuracy: 0.0023
Epoch: 0 | Loss: 2.6840 | Accuracy: 0.0023
Epoch: 0 | Loss: 2.8027 | Accuracy: 0.0023
Epoch: 0 | Loss: 2.9640 | Accuracy: 0.0091
Epoch: 0 | Loss: 3.1433 | Accuracy: 0.0091
Epoch: 0 | Loss: 3.2711 | Accuracy: 0.0114
Epoch: 0 | Loss: 3.3959 | Accuracy: 0.0159
Epoch: 0 | Loss: 3.5298 | Accuracy: 0.0182
Epoch: 0 | Loss: 3.6166 | Accuracy: 0.0250
Epoch: 0 | Loss: 3.7128 | Accuracy: 0.0250
Epoch: 0 | Loss: 3.8309 | Accuracy: 0.0250
Epoch: 0 | Loss: 3.9060 | Accuracy: 0.0227
Epoch: 0 | Loss: 3.9835 | Accuracy: 0.0114
Epoch: 0 | 

accuracy,▁▄▄▅▇▆▅▅▆▇▇▇▇▇█▇▇███▇▇▆▇▇█▇▇▇▇██▇▇▇▇▇▇▇▇
epoch,▁▁▁▁▁▂▂▃▃▃▃▃▃▃▄▅▅▅▅▅▅▅▅▆▆▆▆▆▆▇▇▇▇▇▇▇████
loss,▇█▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁
accuracy,0.95227
epoch,500
loss,0.03328


# Upload model on HuggingFace

In [54]:
import torch.nn as nn

from huggingface_hub import PyTorchModelHubMixin

In [55]:
class CropModelNew(nn.Module, PyTorchModelHubMixin):
    def __init__(self, input_size=7, hidden_1=14, hidden_2=32, output_size=22):
        super(CropModelNew, self).__init__()

        # layers
        self.fc1 = nn.Linear(input_size, hidden_1)
        self.relu1 = nn.ReLU()

        self.fc2 =nn.Linear(hidden_1, hidden_2)
        self.relu2 = nn.ReLU()

        self.fc3 = nn.Linear(hidden_2, output_size)

    def forward(self, x):
        x = self.fc1(x)
        x = self.relu1(x)

        x = self.fc2(x)
        x = self.relu2(x)

        x= self.fc3(x)

        return x

In [56]:
model =
CropModelNew()
optimizer = torch.optim.Adam(model.parameters(), lr=0.001)

SyntaxError: invalid syntax (976101915.py, line 1)

In [ ]:
epoches = 501 

for epoch in range(epoches):
    model.train()
    total_loss = 0

    for batch_X, batch_y in train_batch:
        out = model(batch_X)
        loss = loss_function(out, batch_y)

        optimizer.zero_grad()
        loss.backward()
        optimizer.step()

        total_loss += loss.item()

        # accuracy
        model.eval()
        with torch.no_grad():
            y_pred = model(X_test).argmax(dim=1)
            acc = accuracy_score(y_test, y_pred)

    avg_loss = total_loss / len(train_batch)
    if epoch % 10 == 0:
        print("Epoch: ", " Loss: ", avg_loss, " Accuracy: ", acc)

In [ ]:
repo_id = "Aishwarya240/CropRecommendationModel"

In [ ]:
# Upload model to specific repository
model.push_to_hub(
    repo_id=repo_id,
    config={"input_size": 7, "hidden_1": 14, "hidden_2": 32, "output_size": 22},
    commit_message="Initial commit - create new crop recommendation model"
)

- Load model from hugging face

In [57]:
import torch
import torch.nn as nn
from huggingface_hub import PyTorchModelHubMixin

# You MUST include PyTorchModelHubMixin here for .from_pretrained to exit
class CropRecommendation(nn.Module, PyTorchModelHubMixin):
    def __init__(self, input_size=7, hidden_1=14, hidden_2=32, output_size=22):
        super().__init__()

        # layers
        self.fc1 = nn.Linear(input_size, hidden_1)
        self.relu1 = nn.ReLU()

        self.fc2 =nn.Linear(hidden_1, hidden_2)
        self.relu2 = nn.ReLU()

        self.fc3 = nn.Linear(hidden_2, output_size)

    def forward(self, x):
        x = self.relu1(self.fc1(x))
        x = self.relu2(self.fc2(x))
        x = self.fc3(x)
        return x

# Now this will work
model = CropRecommendation.from_pretrained("Aishwarya240/CropRecommendationModel")
       

In [58]:
model

CropRecommendation(
  (fc1): Linear(in_features=7, out_features=14, bias=True)
  (relu1): ReLU()
  (fc2): Linear(in_features=14, out_features=32, bias=True)
  (relu2): ReLU()
  (fc3): Linear(in_features=32, out_features=22, bias=True)
)

In [59]:
model.eval()
with torch.no_grad():
    y_pred = model(X_test).argmax(dim=1)
    acc = accuracy_score(y_test, y_pred)

In [60]:
acc

0.9613636363636363