# Understanding how to use Batch dataset to train Models

- Lets use batch in our iris dataset

In [1]:
from sklearn.datasets import load_iris

In [2]:
data = load_iris()

In [3]:
X = data["data"]
y = data["target"]

In [4]:
X.shape, y.shape

((150, 4), (150,))

In [5]:
X

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

In [6]:
y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [7]:
from sklearn.model_selection import train_test_split

In [8]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 42)
X_train.shape, X_test.shape, y_train.shape, y_test.shape

((120, 4), (30, 4), (120,), (30,))

In [9]:
import torch
from torch.utils.data import TensorDataset, DataLoader

In [10]:
# Convert train numpy data into tensors
X_train_tensors = torch.tensor(X_train, dtype=torch.float)
y_train_tensors = torch.tensor(y_train, dtype=torch.long)

In [11]:
# convert test numpy data into tensors
X_test_tensors = torch.tensor(X_test, dtype=torch.float)
y_test_tensors = torch.tensor(y_test, dtype=torch.long)

In [12]:
# now lets convert into tensor dataset

train_dataset = TensorDataset(X_train_tensors, y_train_tensors)
test_dataset = TensorDataset(X_test_tensors, y_test_tensors)

In [13]:
list(train_dataset)[:5]

[(tensor([4.6000, 3.6000, 1.0000, 0.2000]), tensor(0)),
 (tensor([5.7000, 4.4000, 1.5000, 0.4000]), tensor(0)),
 (tensor([6.7000, 3.1000, 4.4000, 1.4000]), tensor(1)),
 (tensor([4.8000, 3.4000, 1.6000, 0.2000]), tensor(0)),
 (tensor([4.4000, 3.2000, 1.3000, 0.2000]), tensor(0))]

In [14]:
list(test_dataset)

[(tensor([6.1000, 2.8000, 4.7000, 1.2000]), tensor(1)),
 (tensor([5.7000, 3.8000, 1.7000, 0.3000]), tensor(0)),
 (tensor([7.7000, 2.6000, 6.9000, 2.3000]), tensor(2)),
 (tensor([6.0000, 2.9000, 4.5000, 1.5000]), tensor(1)),
 (tensor([6.8000, 2.8000, 4.8000, 1.4000]), tensor(1)),
 (tensor([5.4000, 3.4000, 1.5000, 0.4000]), tensor(0)),
 (tensor([5.6000, 2.9000, 3.6000, 1.3000]), tensor(1)),
 (tensor([6.9000, 3.1000, 5.1000, 2.3000]), tensor(2)),
 (tensor([6.2000, 2.2000, 4.5000, 1.5000]), tensor(1)),
 (tensor([5.8000, 2.7000, 3.9000, 1.2000]), tensor(1)),
 (tensor([6.5000, 3.2000, 5.1000, 2.0000]), tensor(2)),
 (tensor([4.8000, 3.0000, 1.4000, 0.1000]), tensor(0)),
 (tensor([5.5000, 3.5000, 1.3000, 0.2000]), tensor(0)),
 (tensor([4.9000, 3.1000, 1.5000, 0.1000]), tensor(0)),
 (tensor([5.1000, 3.8000, 1.5000, 0.3000]), tensor(0)),
 (tensor([6.3000, 3.3000, 4.7000, 1.6000]), tensor(1)),
 (tensor([6.5000, 3.0000, 5.8000, 2.2000]), tensor(2)),
 (tensor([5.6000, 2.5000, 3.9000, 1.1000]), tens

In [15]:
# now lets convert our data into batches

train_loader = DataLoader(train_dataset, batch_size=16, shuffle=True)
test_loader = DataLoader(test_dataset, batch_size=2, shuffle=True)

In [16]:
list(train_loader)

[[tensor([[5.1000, 3.7000, 1.5000, 0.4000],
          [7.0000, 3.2000, 4.7000, 1.4000],
          [6.7000, 3.0000, 5.0000, 1.7000],
          [5.0000, 3.5000, 1.3000, 0.3000],
          [5.5000, 2.5000, 4.0000, 1.3000],
          [5.6000, 2.8000, 4.9000, 2.0000],
          [5.0000, 3.6000, 1.4000, 0.2000],
          [4.8000, 3.4000, 1.6000, 0.2000],
          [6.7000, 3.1000, 5.6000, 2.4000],
          [6.5000, 2.8000, 4.6000, 1.5000],
          [5.0000, 2.3000, 3.3000, 1.0000],
          [5.1000, 3.5000, 1.4000, 0.3000],
          [6.0000, 2.2000, 5.0000, 1.5000],
          [5.6000, 2.7000, 4.2000, 1.3000],
          [5.1000, 3.5000, 1.4000, 0.2000],
          [4.9000, 3.0000, 1.4000, 0.2000]]),
  tensor([0, 1, 1, 0, 1, 2, 0, 0, 2, 1, 1, 0, 2, 1, 0, 0])],
 [tensor([[6.7000, 3.3000, 5.7000, 2.5000],
          [6.9000, 3.1000, 4.9000, 1.5000],
          [6.3000, 3.3000, 6.0000, 2.5000],
          [7.2000, 3.6000, 6.1000, 2.5000],
          [6.1000, 3.0000, 4.6000, 1.4000],
          [4.

# Model

In [17]:
import torch.nn as nn

In [18]:
class Model(nn.Module):
    def __init__(self):
        super(Model, self).__init__()

        # layers
        self.fc1 = nn.Linear(4, 8) # input layer
        self.fc2 = nn.Linear(8, 16) # hidden layer
        self.fc3 = nn.Linear(16, 8) # hidden layer
        self.fc4 = nn.Linear(8, 3) # output layer

    def forward(self, x):
        x = self.fc1(x)
        x = self.fc2(x)
        x = self.fc3(x)
        x  = self.fc4(x)

        return x

In [19]:
model = Model()
model

Model(
  (fc1): Linear(in_features=4, out_features=8, bias=True)
  (fc2): Linear(in_features=8, out_features=16, bias=True)
  (fc3): Linear(in_features=16, out_features=8, bias=True)
  (fc4): Linear(in_features=8, out_features=3, bias=True)
)

In [20]:
loss_function = nn.CrossEntropyLoss()
optimizer = torch.optim.Adam(model.parameters(), lr=0.001)

In [21]:
from sklearn.metrics import accuracy_score

In [22]:
epoches = 500

for batch_X, batch_y in train_loader:
    for epoch in range(epoches):
        model.train()

        out = model(batch_X)
        loss = loss_function(out, batch_y)

        optimizer.zero_grad()
        loss.backward()
        optimizer.step()

        # calculate accuracy
        model.eval()
        y_pred = model(X_test_tensors).argmax(dim=1)
        acc = accuracy_score(y_test_tensors, y_pred)

        if epoch % 10 == 0:
            print("Epoch: ", epoch, "Loss: ", loss.item(), "Accuracy: ", acc)

Epoch:  0 Loss:  1.152509093284607 Accuracy:  0.3333333333333333
Epoch:  10 Loss:  1.0672742128372192 Accuracy:  0.5
Epoch:  20 Loss:  1.0316166877746582 Accuracy:  0.5
Epoch:  30 Loss:  0.9922519326210022 Accuracy:  0.4666666666666667
Epoch:  40 Loss:  0.942105770111084 Accuracy:  0.6333333333333333
Epoch:  50 Loss:  0.878763735294342 Accuracy:  0.6333333333333333
Epoch:  60 Loss:  0.8004367351531982 Accuracy:  0.8333333333333334
Epoch:  70 Loss:  0.7103705406188965 Accuracy:  0.8333333333333334
Epoch:  80 Loss:  0.6179868578910828 Accuracy:  0.8333333333333334
Epoch:  90 Loss:  0.534787118434906 Accuracy:  0.8666666666666667
Epoch:  100 Loss:  0.4672417640686035 Accuracy:  0.8666666666666667
Epoch:  110 Loss:  0.41409921646118164 Accuracy:  0.8666666666666667
Epoch:  120 Loss:  0.3702307641506195 Accuracy:  0.8666666666666667
Epoch:  130 Loss:  0.33134204149246216 Accuracy:  0.8666666666666667
Epoch:  140 Loss:  0.2955338954925537 Accuracy:  0.9
Epoch:  150 Loss:  0.2626667022705078 

In [23]:
model.eval()
y_pred = model(X_test_tensors).argmax(dim=1)
accuracy_score(y_test_tensors, y_pred)

0.9666666666666667

# Working with crop recommendation dataset

In [34]:
import pandas as pd

In [35]:
data = pd.read_csv("Datasets/Crop_recommendation.csv")

In [36]:
data.columns

Index(['N', 'P', 'K', 'temperature', 'humidity', 'ph', 'rainfall', 'label'], dtype='str')

In [29]:
data.head()

,N,P,K,temperature,humidity,ph,rainfall,label
0,90,42,43,20.879744,82.002744,6.502985,202.935536,rice
1,85,58,41,21.770462,80.319644,7.038096,226.655537,rice
2,60,55,44,23.004459,82.320763,7.840207,263.964248,rice
3,74,35,40,26.491096,80.158363,6.980401,242.864034,rice
4,78,42,42,20.130175,81.604873,7.628473,262.717340,rice


In [31]:
data.info()

<class 'pandas.DataFrame'>
RangeIndex: 2200 entries, 0 to 2199
Data columns (total 8 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   N            2200 non-null   int64  
 1   P            2200 non-null   int64  
 2   K            2200 non-null   int64  
 3   temperature  2200 non-null   float64
 4   humidity     2200 non-null   float64
 5   ph           2200 non-null   float64
 6   rainfall     2200 non-null   float64
 7   label        2200 non-null   str    
dtypes: float64(4), int64(3), str(1)
memory usage: 137.6 KB


In [77]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()

In [78]:
X = data.drop(["label"], axis=1)
y = data["label"]

label_names = list(set(data.label))

In [79]:
label_names

['apple',
 'mungbean',
 'cotton',
 'muskmelon',
 'orange',
 'blackgram',
 'watermelon',
 'pomegranate',
 'grapes',
 'lentil',
 'coconut',
 'pigeonpeas',
 'banana',
 'rice',
 'mango',
 'mothbeans',
 'maize',
 'chickpea',
 'papaya',
 'jute',
 'kidneybeans',
 'coffee']

In [80]:
y = le.fit_transform(y)
y

array([20, 20, 20, ...,  5,  5,  5], shape=(2200,))

- Lets convert our data into tensors

In [81]:
import torch

In [82]:
X.values[:5]

array([[ 90.        ,  42.        ,  43.        ,  20.87974371,
         82.00274423,   6.50298529, 202.9355362 ],
       [ 85.        ,  58.        ,  41.        ,  21.77046169,
         80.31964408,   7.03809636, 226.6555374 ],
       [ 60.        ,  55.        ,  44.        ,  23.00445915,
         82.3207629 ,   7.84020714, 263.9642476 ],
       [ 74.        ,  35.        ,  40.        ,  26.49109635,
         80.15836264,   6.9804009 , 242.8640342 ],
       [ 78.        ,  42.        ,  42.        ,  20.13017482,
         81.60487287,   7.62847289, 262.7173405 ]])

In [83]:
X = torch.tensor(X.values, dtype=torch.float)
y = torch.tensor(y, dtype=torch.long)

- now let's split our data  

In [84]:
from sklearn.model_selection import train_test_split


In [85]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 42)
X_train.shape, X_test.shape, y_train.shape, y_test.shape

(torch.Size([1760, 7]),
 torch.Size([440, 7]),
 torch.Size([1760]),
 torch.Size([440]))

- now let's convert our data into batch

In [86]:
from torch.utils.data import TensorDataset, DataLoader

In [87]:
train_dataset = TensorDataset(X_train, y_train)
test_dataset = TensorDataset(X_test, y_test)

In [88]:
train_batch = DataLoader(train_dataset, batch_size=32, shuffle=True)

In [89]:
list(train_batch)

[[tensor([[ 66.0000,  44.0000,  20.0000,  19.0781,  69.0230,   6.7400,  80.7252],
          [ 29.0000,  25.0000,  35.0000,  28.3575,  91.6451,   5.5429, 160.7307],
          [ 80.0000,  26.0000,  55.0000,  24.5344,  88.9893,   6.1401,  49.1162],
          [ 13.0000,   5.0000,   8.0000,  23.8534,  90.1052,   7.4747, 103.9232],
          [  9.0000,  77.0000,  17.0000,  21.6585,  63.5834,   6.2807,  38.0766],
          [ 12.0000,  63.0000,  17.0000,  18.3589,  19.3770,   5.7171, 138.4148],
          [ 39.0000, 138.0000, 203.0000,  21.1934,  82.3310,   6.3994,  74.6283],
          [119.0000,  25.0000,  51.0000,  26.4733,  80.9225,   6.2838,  53.6574],
          [ 15.0000,  11.0000,  38.0000,  23.1281,  92.6833,   6.6306, 109.3930],
          [  5.0000,  16.0000,  31.0000,  35.9605,  48.6968,   4.5557,  98.0064],
          [  9.0000,  16.0000,  39.0000,  18.4116,  91.1193,   6.1012, 105.1835],
          [ 99.0000,  16.0000,  30.0000,  23.5265,  65.4434,   6.3928, 186.1728],
          [ 28.0

In [90]:
import torch.nn as nn

In [117]:
class CropModel(nn.Module):
    def __init__(self):
        super(CropModel, self).__init__()

        self.fc1 = nn.Linear(7, 14)
        self.relu1 = nn.ReLU()

        self.fc2 = nn.Linear(14, 32)
        self.relu2 = nn.ReLU()

        self.fc3 = nn.Linear(32, 22)
        
    def forward(self, x):
        x = self.fc1(x)
        x = self.relu1(x)

        x = self.fc2(x)
        x = self.relu2(x)

        x = self.fc3(x)
        
        return x

In [118]:
model = CropModel()

In [119]:
model

CropModel(
  (fc1): Linear(in_features=7, out_features=14, bias=True)
  (relu1): ReLU()
  (fc2): Linear(in_features=14, out_features=32, bias=True)
  (relu2): ReLU()
  (fc3): Linear(in_features=32, out_features=22, bias=True)
)

In [120]:
loss_function = nn.CrossEntropyLoss()
optimizer = torch.optim.Adam(model.parameters(), lr=0.001)

In [121]:
from sklearn.metrics import accuracy_score

In [122]:
epoches = 500

for batch_X, batch_y in train_batch:
    for epoch in range(epoches):
        model.train()

        out = model(batch_X)
        loss = loss_function(out, batch_y)

        optimizer.zero_grad()
        loss.backward()
        optimizer.step()

        # accuracy
        y_pred = model(X_test).argmax(dim=1)
        acc = accuracy_score(y_test, y_pred)

        if epoch % 10 == 0:
            print("Epoch: ", epoch, " Loss: ", loss.item(), " Accuracy: ", acc)

Epoch:  0  Loss:  9.572223663330078  Accuracy:  0.04318181818181818
Epoch:  10  Loss:  6.241621017456055  Accuracy:  0.04318181818181818
Epoch:  20  Loss:  4.35382604598999  Accuracy:  0.09545454545454546
Epoch:  30  Loss:  3.38084077835083  Accuracy:  0.13636363636363635
Epoch:  40  Loss:  2.7500619888305664  Accuracy:  0.15454545454545454
Epoch:  50  Loss:  2.267238140106201  Accuracy:  0.17727272727272728
Epoch:  60  Loss:  1.8732619285583496  Accuracy:  0.21818181818181817
Epoch:  70  Loss:  1.5502971410751343  Accuracy:  0.31136363636363634
Epoch:  80  Loss:  1.3150328397750854  Accuracy:  0.3386363636363636
Epoch:  90  Loss:  1.1259450912475586  Accuracy:  0.3613636363636364
Epoch:  100  Loss:  0.9431129693984985  Accuracy:  0.3886363636363636
Epoch:  110  Loss:  0.7778152823448181  Accuracy:  0.45
Epoch:  120  Loss:  0.6339091062545776  Accuracy:  0.46136363636363636
Epoch:  130  Loss:  0.5200444459915161  Accuracy:  0.48409090909090907
Epoch:  140  Loss:  0.4292992353439331  Ac

- evaluate model

In [124]:
model.eval()

y_pred = model(X_test).argmax(dim=1)
accuracy_score(y_test, y_pred)


0.8909090909090909

In [125]:
from sklearn.metrics import classification_report, confusion_matrix

In [126]:
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        23
           1       0.88      1.00      0.93        21
           2       0.86      0.95      0.90        20
           3       1.00      1.00      1.00        26
           4       0.79      1.00      0.89        27
           5       0.92      0.71      0.80        17
           6       0.84      0.94      0.89        17
           7       1.00      1.00      1.00        14
           8       0.68      0.91      0.78        23
           9       0.70      0.95      0.81        20
          10       0.91      0.91      0.91        11
          11       0.94      0.76      0.84        21
          12       1.00      0.89      0.94        19
          13       0.88      0.62      0.73        24
          14       0.90      1.00      0.95        19
          15       1.00      1.00      1.00        17
          16       1.00      1.00      1.00        14
          17       0.94    

- Using wandb to visualize performance.

In [128]:
model = CropModel()
optimizer = torch.optim.Adam(model.parameters(), lr=0.001)

In [130]:
import wandb
from sklearn.metrics import accuracy_score

def init_wandb(batch_size):
    # Returning the run object so its accessible
    return wandb.init(
        entity="aishwaryapatil845-aish-com",
        project="Crop_Recommendation_New_Model",
        name=f"Model-BS-{batch_size}",
        config={
            "learning_rate": 0.001,
            "architecture": "FNN",
            "dataset": "crop_recommendation",
            "epochs": 501,
        }
    )

# Initialize the run 
run = init_wandb(batch_size=32)
epochs = 501

for epoch in range(epochs):
    model.train()
    total_loss = 0

    for batch_X, batch_y in train_batch:
        # Standard Training Step
        out = model(batch_X)
        loss = loss_function(out, batch_y)

        optimizer.zero_grad()
        loss.backward()
        optimizer.step()

        total_loss += loss.item()

        # Evaluation
        model.eval()
        with torch.no_grad():
            y_pred = model(X_test).argmax(dim=1)
            acc = accuracy_score(y_test.cpu(), y_pred.cpu())

            # Log metrics once per epoch
        avg_loss = total_loss / len(train_batch)
        if epoch % 10 == 0:
            print(f"Epoch: {epoch} | Loss: {avg_loss:.4f} | Accuracy: {acc:.4f}")
            run.log({"loss": avg_loss, "accuracy": acc, "epoch": epoch})
            
#Close the W&B run
run.finish()


wandb: ERROR Failed to detect the name of this notebook. You can set it manually with the WANDB_NOTEBOOK_NAME environment variable to enable code saving.
wandb: [wandb.login()] Loaded credentials for https://api.wandb.ai from /home/aishwarya/.netrc.
wandb: Currently logged in as: aishwaryapatil845 (aishwaryapatil845-aish-com) to https://api.wandb.ai. Use `wandb login --relogin` to force relogin


Epoch: 0 | Loss: 0.1334 | Accuracy: 0.0273
Epoch: 0 | Loss: 0.2683 | Accuracy: 0.0295
Epoch: 0 | Loss: 0.3842 | Accuracy: 0.0273
Epoch: 0 | Loss: 0.5046 | Accuracy: 0.0364
Epoch: 0 | Loss: 0.6056 | Accuracy: 0.0432
Epoch: 0 | Loss: 0.7063 | Accuracy: 0.0477
Epoch: 0 | Loss: 0.8015 | Accuracy: 0.0545
Epoch: 0 | Loss: 0.8930 | Accuracy: 0.0545
Epoch: 0 | Loss: 0.9784 | Accuracy: 0.0477
Epoch: 0 | Loss: 1.0805 | Accuracy: 0.0432
Epoch: 0 | Loss: 1.1541 | Accuracy: 0.0432
Epoch: 0 | Loss: 1.2455 | Accuracy: 0.0477
Epoch: 0 | Loss: 1.3297 | Accuracy: 0.0568
Epoch: 0 | Loss: 1.4100 | Accuracy: 0.0682
Epoch: 0 | Loss: 1.4947 | Accuracy: 0.0705
Epoch: 0 | Loss: 1.5592 | Accuracy: 0.0795
Epoch: 0 | Loss: 1.6356 | Accuracy: 0.0864
Epoch: 0 | Loss: 1.7181 | Accuracy: 0.0909
Epoch: 0 | Loss: 1.7823 | Accuracy: 0.1045
Epoch: 0 | Loss: 1.8508 | Accuracy: 0.1159
Epoch: 0 | Loss: 1.9115 | Accuracy: 0.1227
Epoch: 0 | Loss: 1.9848 | Accuracy: 0.1273
Epoch: 0 | Loss: 2.0427 | Accuracy: 0.1409
Epoch: 0 | 

accuracy,▁▁▁▄▃▄▃▄▅▆▂▅▅▅▄▃▆▅▅▃▄▄▅▅▅▄▆▆▆▄▅▄▅▆▆▅▄█▆▅
epoch,▁▁▁▂▂▂▂▂▂▂▃▃▃▃▃▄▄▄▄▄▄▄▄▄▅▅▅▅▅▅▆▆▆▆▇▇▇▇▇█
loss,█▁▂▂▂▁▁▂▁▁▂▂▁▂▁▂▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁
accuracy,0.93864
epoch,500
loss,0.06297


# Upload model on HuggingFace

In [133]:
import torch.nn as nn

from huggingface_hub import PyTorchModelHubMixin

In [135]:
class CropModelNew(nn.Module, PyTorchModelHubMixin):
    def __init__(self, input_size=7, hidden_1=14, hidden_2=32, output_size=22):
        super(CropModelNew, self).__init__()

        # layers
        self.fc1 = nn.Linear(input_size, hidden_1)
        self.relu1 = nn.ReLU()

        self.fc2 =nn.Linear(hidden_1, hidden_2)
        self.relu2 = nn.ReLU()

        self.fc3 = nn.Linear(hidden_2, output_size)

    def forward(self, x):
        x = self.fc1(x)
        x = self.relu1(x)

        x = self.fc2(x)
        x = self.relu2(x)

        x= self.fc3(x)

        return x

In [136]:
model =
CropModelNew()
optimizer = torch.optim.Adam(model.parameters(), lr=0.001)

In [137]:
epoches = 501 

for epoch in range(epoches):
    model.train()
    total_loss = 0

    for batch_X, batch_y in train_batch:
        out = model(batch_X)
        loss = loss_function(out, batch_y)

        optimizer.zero_grad()
        loss.backward()
        optimizer.step()

        total_loss += loss.item()

        # accuracy
        model.eval()
        with torch.no_grad():
            y_pred = model(X_test).argmax(dim=1)
            acc = accuracy_score(y_test, y_pred)

    avg_loss = total_loss / len(train_batch)
    if epoch % 10 == 0:
        print("Epoch: ", " Loss: ", avg_loss, " Accuracy: ", acc)

Epoch:   Loss:  6.559094979546287  Accuracy:  0.18409090909090908
Epoch:   Loss:  0.24396044937047093  Accuracy:  0.9181818181818182
Epoch:   Loss:  0.14536010602658445  Accuracy:  0.9454545454545454
Epoch:   Loss:  0.13443796245211906  Accuracy:  0.9318181818181818
Epoch:   Loss:  0.09672072353688153  Accuracy:  0.9431818181818182
Epoch:   Loss:  0.08786720118739388  Accuracy:  0.9409090909090909
Epoch:   Loss:  0.08884044397961009  Accuracy:  0.95
Epoch:   Loss:  0.09009370311925358  Accuracy:  0.9477272727272728
Epoch:   Loss:  0.07670890539884567  Accuracy:  0.9681818181818181
Epoch:   Loss:  0.06031695732592859  Accuracy:  0.9681818181818181
Epoch:   Loss:  0.06460365209389816  Accuracy:  0.9681818181818181
Epoch:   Loss:  0.06590992616150868  Accuracy:  0.9568181818181818
Epoch:   Loss:  0.06327022817832502  Accuracy:  0.9636363636363636
Epoch:   Loss:  0.0600397328465161  Accuracy:  0.9568181818181818
Epoch:   Loss:  0.04991638900034807  Accuracy:  0.9613636363636363
Epoch:   Lo

In [138]:
repo_id = "Aishwarya240/CropRecommendationModel"

In [140]:
# Upload model to specific repository
model.push_to_hub(
    repo_id=repo_id,
    config={"input_size": 7, "hidden_1": 14, "hidden_2": 32, "output_size": 22},
    commit_message="Initial commit - create new crop recommendation model"
)

Processing Files (0 / 0): |          |  0.00B /  0.00B            

New Data Upload: |          |  0.00B /  0.00B            

No files have been modified since last commit. Skipping to prevent empty commit.


CommitInfo(commit_url='https://huggingface.co/Aishwarya240/CropRecommendationModel/commit/2656d70ba7edbf0dfa1744fc3ae8ebc1467df520', commit_message='Initial commit - create new crop recommendation model', commit_description='', oid='2656d70ba7edbf0dfa1744fc3ae8ebc1467df520', pr_url=None, repo_url=RepoUrl('https://huggingface.co/Aishwarya240/CropRecommendationModel', endpoint='https://huggingface.co', repo_type='model', repo_id='Aishwarya240/CropRecommendationModel'), pr_revision=None, pr_num=None)

- Load model from hugging face

In [143]:
import torch
import torch.nn as nn
from huggingface_hub import PyTorchModelHubMixin

# You MUST include PyTorchModelHubMixin here for .from_pretrained to exit
class CropRecommendation(nn.Module, PyTorchModelHubMixin):
    def __init__(self, input_size=7, hidden_1=14, hidden_2=32, output_size=22):
        super().__init__()

        # layers
        self.fc1 = nn.Linear(input_size, hidden_1)
        self.relu1 = nn.ReLU()

        self.fc2 =nn.Linear(hidden_1, hidden_2)
        self.relu2 = nn.ReLU()

        self.fc3 = nn.Linear(hidden_2, output_size)

    def forward(self, x):
        x = self.relu1(self.fc1(x))
        x = self.relu2(self.fc2(x))
        x = self.fc3(x)
        return x

# Now this will work
model = CropRecommendation.from_pretrained("Aishwarya240/CropRecommendationModel")
       

config.json:   0%|          | 0.00/78.0 [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/5.69k [00:00<?, ?B/s]

In [144]:
model

CropRecommendation(
  (fc1): Linear(in_features=7, out_features=14, bias=True)
  (relu1): ReLU()
  (fc2): Linear(in_features=14, out_features=32, bias=True)
  (relu2): ReLU()
  (fc3): Linear(in_features=32, out_features=22, bias=True)
)

In [145]:
model.eval()
with torch.no_grad():
    y_pred = model(X_test).

CropRecommendation(
  (fc1): Linear(in_features=7, out_features=14, bias=True)
  (relu1): ReLU()
  (fc2): Linear(in_features=14, out_features=32, bias=True)
  (relu2): ReLU()
  (fc3): Linear(in_features=32, out_features=22, bias=True)
)