# Understanding how to use Batch dataset to train Models

- Lets use batch in our iris dataset

In [1]:
from sklearn.datasets import load_iris

In [2]:
data = load_iris()

In [3]:
X = data["data"]
y = data["target"]

In [5]:
X.shape, y.shape

((150, 4), (150,))

In [6]:
X

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

In [7]:
y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [8]:
from sklearn.model_selection import train_test_split

In [10]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 42)
X_train.shape, X_test.shape, y_train.shape, y_test.shape

((120, 4), (30, 4), (120,), (30,))

In [16]:
import torch
from torch.utils.data import TensorDataset, DataLoader

In [17]:
# Convert train numpy data into tensors
X_train_tensors = torch.tensor(X_train, dtype=torch.float)
y_train_tensors = torch.tensor(y_train, dtype=torch.long)

In [19]:
# convert test numpy data into tensors
X_test_tensors = torch.tensor(X_test, dtype=torch.float)
y_test_tensors = torch.tensor(y_test, dtype=torch.long)

In [20]:
# now lets convert into tensor dataset

train_dataset = TensorDataset(X_train_tensors, y_train_tensors)
test_dataset = TensorDataset(X_test_tensors, y_test_tensors)

In [21]:
list(train_dataset)[:5]

[(tensor([4.6000, 3.6000, 1.0000, 0.2000]), tensor(0)),
 (tensor([5.7000, 4.4000, 1.5000, 0.4000]), tensor(0)),
 (tensor([6.7000, 3.1000, 4.4000, 1.4000]), tensor(1)),
 (tensor([4.8000, 3.4000, 1.6000, 0.2000]), tensor(0)),
 (tensor([4.4000, 3.2000, 1.3000, 0.2000]), tensor(0))]

In [22]:
list(test_dataset)

[(tensor([6.1000, 2.8000, 4.7000, 1.2000]), tensor(1)),
 (tensor([5.7000, 3.8000, 1.7000, 0.3000]), tensor(0)),
 (tensor([7.7000, 2.6000, 6.9000, 2.3000]), tensor(2)),
 (tensor([6.0000, 2.9000, 4.5000, 1.5000]), tensor(1)),
 (tensor([6.8000, 2.8000, 4.8000, 1.4000]), tensor(1)),
 (tensor([5.4000, 3.4000, 1.5000, 0.4000]), tensor(0)),
 (tensor([5.6000, 2.9000, 3.6000, 1.3000]), tensor(1)),
 (tensor([6.9000, 3.1000, 5.1000, 2.3000]), tensor(2)),
 (tensor([6.2000, 2.2000, 4.5000, 1.5000]), tensor(1)),
 (tensor([5.8000, 2.7000, 3.9000, 1.2000]), tensor(1)),
 (tensor([6.5000, 3.2000, 5.1000, 2.0000]), tensor(2)),
 (tensor([4.8000, 3.0000, 1.4000, 0.1000]), tensor(0)),
 (tensor([5.5000, 3.5000, 1.3000, 0.2000]), tensor(0)),
 (tensor([4.9000, 3.1000, 1.5000, 0.1000]), tensor(0)),
 (tensor([5.1000, 3.8000, 1.5000, 0.3000]), tensor(0)),
 (tensor([6.3000, 3.3000, 4.7000, 1.6000]), tensor(1)),
 (tensor([6.5000, 3.0000, 5.8000, 2.2000]), tensor(2)),
 (tensor([5.6000, 2.5000, 3.9000, 1.1000]), tens

In [23]:
# now lets convert our data into batches

train_loader = DataLoader(train_dataset, batch_size=16, shuffle=True)
test_loader = DataLoader(test_dataset, batch_size=2, shuffle=True)

In [24]:
list(train_loader)

[[tensor([[4.9000, 3.1000, 1.5000, 0.2000],
          [5.0000, 3.0000, 1.6000, 0.2000],
          [5.1000, 3.8000, 1.6000, 0.2000],
          [6.7000, 3.0000, 5.0000, 1.7000],
          [6.5000, 3.0000, 5.5000, 1.8000],
          [6.2000, 3.4000, 5.4000, 2.3000],
          [5.0000, 2.3000, 3.3000, 1.0000],
          [5.0000, 3.2000, 1.2000, 0.2000],
          [5.2000, 4.1000, 1.5000, 0.1000],
          [5.6000, 2.7000, 4.2000, 1.3000],
          [5.2000, 2.7000, 3.9000, 1.4000],
          [7.7000, 2.8000, 6.7000, 2.0000],
          [5.8000, 2.7000, 4.1000, 1.0000],
          [5.0000, 3.4000, 1.5000, 0.2000],
          [5.5000, 2.5000, 4.0000, 1.3000],
          [5.6000, 3.0000, 4.5000, 1.5000]]),
  tensor([0, 0, 0, 1, 2, 2, 1, 0, 0, 1, 1, 2, 1, 0, 1, 1])],
 [tensor([[7.7000, 3.8000, 6.7000, 2.2000],
          [6.7000, 3.1000, 4.7000, 1.5000],
          [5.1000, 3.5000, 1.4000, 0.2000],
          [6.0000, 3.4000, 4.5000, 1.6000],
          [5.0000, 2.0000, 3.5000, 1.0000],
          [5.

# Model

In [27]:
import torch.nn as nn

In [36]:
class Model(nn.Module):
    def __init__(self):
        super(Model, self).__init__()

        # layers
        self.fc1 = nn.Linear(4, 8) # input layer
        self.fc2 = nn.Linear(8, 16) # hidden layer
        self.fc3 = nn.Linear(16, 8) # hidden layer
        self.fc4 = nn.Linear(8, 3) # output layer

    def forward(self, x):
        x = self.fc1(x)
        x = self.fc2(x)
        x = self.fc3(x)
        x  = self.fc4(x)

        return x

In [30]:
model = Model()
model

Model(
  (fc1): Linear(in_features=4, out_features=8, bias=True)
  (fc2): Linear(in_features=8, out_features=16, bias=True)
  (fc3): Linear(in_features=16, out_features=8, bias=True)
  (fc4): Linear(in_features=8, out_features=3, bias=True)
)

In [31]:
loss_function = nn.CrossEntropyLoss()
optimizer = torch.optim.Adam(model.parameters(), lr=0.001)

In [32]:
from sklearn.metrics import accuracy_score

In [34]:
epoches = 500

for batch_X, batch_y in train_loader:
    for epoch in range(epoches):
        model.train()

        out = model(batch_X)
        loss = loss_function(out, batch_y)

        optimizer.zero_grad()
        loss.backward()
        optimizer.step()

        # calculate accuracy
        model.eval()
        y_pred = model(X_test_tensors).argmax(dim=1)
        acc = accuracy_score(y_test_tensors, y_pred)

        if epoch % 10 == 0:
            print("Epoch: ", epoch, "Loss: ", loss.item(), "Accuracy: ", acc)

Epoch:  0 Loss:  0.5296902656555176 Accuracy:  0.9666666666666667
Epoch:  10 Loss:  0.22280138731002808 Accuracy:  0.9333333333333333
Epoch:  20 Loss:  0.166506826877594 Accuracy:  0.9
Epoch:  30 Loss:  0.1448114812374115 Accuracy:  0.9333333333333333
Epoch:  40 Loss:  0.11797304451465607 Accuracy:  0.9333333333333333
Epoch:  50 Loss:  0.10429145395755768 Accuracy:  0.9333333333333333
Epoch:  60 Loss:  0.09864065796136856 Accuracy:  0.9333333333333333
Epoch:  70 Loss:  0.09515413641929626 Accuracy:  0.9333333333333333
Epoch:  80 Loss:  0.09353124350309372 Accuracy:  0.9333333333333333
Epoch:  90 Loss:  0.09273805469274521 Accuracy:  0.9333333333333333
Epoch:  100 Loss:  0.09221083670854568 Accuracy:  0.9333333333333333
Epoch:  110 Loss:  0.09181352704763412 Accuracy:  0.9333333333333333
Epoch:  120 Loss:  0.0914420336484909 Accuracy:  0.9333333333333333
Epoch:  130 Loss:  0.09108143299818039 Accuracy:  0.9333333333333333
Epoch:  140 Loss:  0.09072098135948181 Accuracy:  0.9333333333333

In [35]:
model.eval()
y_pred = model(X_test_tensors).argmax(dim=1)
accuracy_score(y_test_tensors, y_pred)

0.9666666666666667