# Crop Recommendation Model

## Load Data 

In [1]:
import pandas as pd

In [2]:
data = pd.read_csv("Datasets/Crop_recommendation.csv")
data.head()

,N,P,K,temperature,humidity,ph,rainfall,label
0,90,42,43,20.879744,82.002744,6.502985,202.935536,rice
1,85,58,41,21.770462,80.319644,7.038096,226.655537,rice
2,60,55,44,23.004459,82.320763,7.840207,263.964248,rice
3,74,35,40,26.491096,80.158363,6.980401,242.864034,rice
4,78,42,42,20.130175,81.604873,7.628473,262.717340,rice


In [3]:
data.info()

<class 'pandas.DataFrame'>
RangeIndex: 2200 entries, 0 to 2199
Data columns (total 8 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   N            2200 non-null   int64  
 1   P            2200 non-null   int64  
 2   K            2200 non-null   int64  
 3   temperature  2200 non-null   float64
 4   humidity     2200 non-null   float64
 5   ph           2200 non-null   float64
 6   rainfall     2200 non-null   float64
 7   label        2200 non-null   str    
dtypes: float64(4), int64(3), str(1)
memory usage: 137.6 KB


In [4]:
# set example
a = {1, 2, 3, 1, 1, 2, 4}
a

{1, 2, 3, 4}

In [5]:
label_names = list(set(data["label"]))
label_names

['cotton',
 'rice',
 'papaya',
 'grapes',
 'muskmelon',
 'apple',
 'watermelon',
 'pigeonpeas',
 'mungbean',
 'chickpea',
 'kidneybeans',
 'coffee',
 'mango',
 'mothbeans',
 'lentil',
 'maize',
 'pomegranate',
 'coconut',
 'blackgram',
 'orange',
 'jute',
 'banana']

In [6]:
len(label_names)

22

In [7]:
data

,N,P,K,temperature,humidity,ph,rainfall,label
0,90,42,43,20.879744,82.002744,6.502985,202.935536,rice
1,85,58,41,21.770462,80.319644,7.038096,226.655537,rice
2,60,55,44,23.004459,82.320763,7.840207,263.964248,rice
3,74,35,40,26.491096,80.158363,6.980401,242.864034,rice
4,78,42,42,20.130175,81.604873,7.628473,262.717340,rice
...,...,...,...,...,...,...,...,...
2195,107,34,32,26.774637,66.413269,6.780064,177.774507,coffee
2196,99,15,27,27.417112,56.636362,6.086922,127.924610,coffee
2197,118,33,30,24.131797,67.225123,6.362608,173.322839,coffee
2198,117,32,34,26.272418,52.127394,6.758793,127.175293,coffee


# Feature
- Split our data into input and output values
- Input values will be stored in X and output values will be stored in y variables.

In [8]:
data.head()

,N,P,K,temperature,humidity,ph,rainfall,label
0,90,42,43,20.879744,82.002744,6.502985,202.935536,rice
1,85,58,41,21.770462,80.319644,7.038096,226.655537,rice
2,60,55,44,23.004459,82.320763,7.840207,263.964248,rice
3,74,35,40,26.491096,80.158363,6.980401,242.864034,rice
4,78,42,42,20.130175,81.604873,7.628473,262.717340,rice


In [9]:
X = data.drop(["label"], axis=1)
y = data["label"]

In [10]:
X.head()

,N,P,K,temperature,humidity,ph,rainfall
0,90,42,43,20.879744,82.002744,6.502985,202.935536
1,85,58,41,21.770462,80.319644,7.038096,226.655537
2,60,55,44,23.004459,82.320763,7.840207,263.964248
3,74,35,40,26.491096,80.158363,6.980401,242.864034
4,78,42,42,20.130175,81.604873,7.628473,262.717340


In [11]:
y.head()

0    rice
1    rice
2    rice
3    rice
4    rice
Name: label, dtype: str

In [12]:
X.shape, y.shape

((2200, 7), (2200,))

- Let's convert 'y' variable into integer data type.

In [13]:
from sklearn.preprocessing import LabelEncoder

In [14]:
le = LabelEncoder()

y = le.fit_transform(y)
y[:5]

array([20, 20, 20, 20, 20])

- Lets convert our data variables `X` and `y` into pytorch tensors.

In [15]:
import torch

In [16]:
X_tensors = torch.tensor(X.values, dtype=torch.float)
y_tensors = torch.tensor(y, dtype=torch.long)

In [17]:
X_tensors, X_tensors.ndim, X_tensors.shape

(tensor([[ 90.0000,  42.0000,  43.0000,  ...,  82.0027,   6.5030, 202.9355],
         [ 85.0000,  58.0000,  41.0000,  ...,  80.3196,   7.0381, 226.6555],
         [ 60.0000,  55.0000,  44.0000,  ...,  82.3208,   7.8402, 263.9642],
         ...,
         [118.0000,  33.0000,  30.0000,  ...,  67.2251,   6.3626, 173.3228],
         [117.0000,  32.0000,  34.0000,  ...,  52.1274,   6.7588, 127.1753],
         [104.0000,  18.0000,  30.0000,  ...,  60.3965,   6.7798, 140.9370]]),
 2,
 torch.Size([2200, 7]))

In [18]:
y_tensors, y_tensors.ndim, y_tensors.shape

(tensor([20, 20, 20,  ...,  5,  5,  5]), 1, torch.Size([2200]))

## Train test split

In [19]:
from sklearn.model_selection import train_test_split

In [20]:
X_train, X_test, y_train, y_test = train_test_split(X_tensors, y_tensors, test_size=0.2, random_state=42)

In [21]:
X_train.shape, X_test.shape, y_train.shape, y_test.shape

(torch.Size([1760, 7]),
 torch.Size([440, 7]),
 torch.Size([1760]),
 torch.Size([440]))

# Model training

In [22]:
import torch.nn as nn


In [23]:
class CropRecommendationModel(nn.Module):
    def __init__(self):
        super(CropRecommendationModel, self).__init__()

        # layers
        self.fc1 = nn.Linear(7, 14)
        # ------ hidden layer
        self.fc2 = nn.Linear(14, 28)
        self.fc3 = nn.Linear(28, 56)
        self.fc4 = nn.Linear(56, 34)
        # -------
        self.fc5 = nn.Linear(34, 22) # output layer

    def forward(self, x):
        x = self.fc1(x) # input layer

        # hidden layer
        x = self.fc2(x)
        x = self.fc3(x)
        x = self.fc4(x)

        x = self.fc5(x) # output layer

    def forward(self, x):
        x = self.fc1(x) # input layer 
        
        # Hidden layer
        x = self.fc2(x)
        x = self.fc3(x)
        x = self.fc4(x)

        x = self.fc5(x) # output layer

        return x

In [24]:
model = CropRecommendationModel()

In [25]:
model


CropRecommendationModel(
  (fc1): Linear(in_features=7, out_features=14, bias=True)
  (fc2): Linear(in_features=14, out_features=28, bias=True)
  (fc3): Linear(in_features=28, out_features=56, bias=True)
  (fc4): Linear(in_features=56, out_features=34, bias=True)
  (fc5): Linear(in_features=34, out_features=22, bias=True)
)

In [26]:
loss_function = nn.CrossEntropyLoss()

optimizer = torch.optim.Adam(model.parameters(), lr=0.001)

In [27]:
# Training loop 
epoches = 100

for epoch in range(epoches):
    model.train()

    out = model(X_tensors)
    loss = loss_function(out, y_tensors.long().squeeze())

    optimizer.zero_grad()
    loss.backward()
    optimizer.step()

    if epoch % 10 == 0 :
        print("Epoch: ", epoch, "Loss value: ", loss.item())
        

Epoch:  0 Loss value:  8.878954887390137
Epoch:  10 Loss value:  2.9194064140319824
Epoch:  20 Loss value:  2.101060628890991
Epoch:  30 Loss value:  1.6371562480926514
Epoch:  40 Loss value:  1.3632235527038574
Epoch:  50 Loss value:  1.1494251489639282
Epoch:  60 Loss value:  0.9766015410423279
Epoch:  70 Loss value:  0.8363673090934753
Epoch:  80 Loss value:  0.7229306697845459
Epoch:  90 Loss value:  0.6321389079093933


In [28]:
y_pred = model(X_test).argmax(dim=1)

In [29]:
from sklearn.metrics import accuracy_score
print(accuracy_score(y_test, y_pred))

0.8386363636363636


# Implement on wandb

In [30]:
import wandb

In [31]:
model = CropRecommendationModel()
optimizer = torch.optim.Adam(model.parameters(), lr=0.001)

In [32]:
run = wandb.init(
    # Set the wandb entity where your project will be logged (generally your team name).
    entity="aishwaryapatil845-aish-com",
    # Set the wandb project where this run will be logged.
    project="Crop_Recommendation",
    name="Model-epoch-100",
    # Track hyperparameters and run metadata.
    config={
        "learning_rate": 0.001,
        "architecture": "FNN",
        "dataset": "crop_recommndation",
        "epochs": 100,
    },
)

# Training loop 
epoches = 100

for epoch in range(epoches):
    model.train()

    out = model(X_tensors)
    loss = loss_function(out, y_tensors.long().squeeze())

    optimizer.zero_grad()
    loss.backward()
    optimizer.step()

    # accuracy
    model.eval()
    y_pred = model(X_test).argmax(dim=1)
    acc = accuracy_score(y_test, y_pred)

    if epoch % 10 == 0 :
        print("Epoch: ", epoch, "Loss value: ", loss.item())
        run.log({"loss": loss.item(), "epoch": epoch, "accuracy": acc})

wandb: ERROR Failed to detect the name of this notebook. You can set it manually with the WANDB_NOTEBOOK_NAME environment variable to enable code saving.
wandb: [wandb.login()] Loaded credentials for https://api.wandb.ai from /home/aishwarya/.netrc.
wandb: Currently logged in as: aishwaryapatil845 (aishwaryapatil845-aish-com) to https://api.wandb.ai. Use `wandb login --relogin` to force relogin


Epoch:  0 Loss value:  9.31525707244873
Epoch:  10 Loss value:  3.140000343322754
Epoch:  20 Loss value:  2.2627012729644775
Epoch:  30 Loss value:  1.8019658327102661
Epoch:  40 Loss value:  1.4659464359283447
Epoch:  50 Loss value:  1.2216438055038452
Epoch:  60 Loss value:  1.0205583572387695
Epoch:  70 Loss value:  0.8522229194641113
Epoch:  80 Loss value:  0.7160545587539673
Epoch:  90 Loss value:  0.6083643436431885


### Using ReLU activation function


In [33]:
class CropRecommendationModelReLU(nn.Module):
    def __init__(self):
        super(CropRecommendationModelReLU, self).__init__()

        # layers
        self.fc1 = nn.Linear(7, 14)
        self.relu1 = nn.ReLU()
        
        # ------ hidden layer
        self.fc2 = nn.Linear(14, 28)
        self.relu2 = nn.ReLU()
        self.do1 = nn.Dropout(0.2)
        
        self.fc3 = nn.Linear(28, 56)
        self.relu3 = nn.ReLU()
        self.do2 = nn.Dropout(0.2)
        
        self.fc4 = nn.Linear(56, 34)
        self.relu4 = nn.ReLU()
        self.do3 = nn.Dropout(0.1)
        # -------
        self.fc5 = nn.Linear(34, 22) # output layer

    def forward(self, x):
        x = self.fc1(x) # input layer
        x = self.relu1(x)
        

        # hidden layer
        x = self.fc2(x)
        x = self.relu2(x)
        x = self.do1(x)
        
        x = self.fc3(x)
        x = self.relu3(x)
        x = self.do2(x)
        
        x = self.fc4(x)
        x = self.relu4(x)
        x = self.do3(x)

        x = self.fc5(x) # output layer

        return x

In [34]:
model = CropRecommendationModelReLU()

In [35]:
model

CropRecommendationModelReLU(
  (fc1): Linear(in_features=7, out_features=14, bias=True)
  (relu1): ReLU()
  (fc2): Linear(in_features=14, out_features=28, bias=True)
  (relu2): ReLU()
  (do1): Dropout(p=0.2, inplace=False)
  (fc3): Linear(in_features=28, out_features=56, bias=True)
  (relu3): ReLU()
  (do2): Dropout(p=0.2, inplace=False)
  (fc4): Linear(in_features=56, out_features=34, bias=True)
  (relu4): ReLU()
  (do3): Dropout(p=0.1, inplace=False)
  (fc5): Linear(in_features=34, out_features=22, bias=True)
)

In [36]:
optimizer = torch.optim.Adam(model.parameters(), lr=0.001)

In [37]:
run = wandb.init(
    # Set the wandb entity where your project will be logged (generally your team name).
    entity="aishwaryapatil845-aish-com",
    # Set the wandb project where this run will be logged.
    project="Crop_Recommendation",
    name="Model-epoch-500-relu-dropout",
    # Track hyperparameters and run metadata.
    config={
        "learning_rate": 0.001,
        "architecture": "FNN",
        "dataset": "crop_recommndation",
        "epochs": 500,
    },
)

# Training loop 
epoches = 500

for epoch in range(epoches):
    model.train()

    out = model(X_tensors)
    loss = loss_function(out, y_tensors)

    optimizer.zero_grad()
    loss.backward()
    optimizer.step()

    # accuracy
    model.eval()
    y_pred = model(X_test).argmax(dim=1)
    acc = accuracy_score(y_test, y_pred)

    if epoch % 10 == 0 :
        print("Epoch: ", epoch, "Loss value: ", loss.item())
        run.log({"loss": loss.item(), "epoch": epoch, "accuracy": acc})

accuracy,▁▃▃▄▅▆▇▇██
epoch,▁▂▃▃▄▅▆▆▇█
loss,█▃▂▂▂▁▁▁▁▁
accuracy,0.83864
epoch,90
loss,0.60836


Epoch:  0 Loss value:  3.3611056804656982
Epoch:  10 Loss value:  2.91513729095459
Epoch:  20 Loss value:  2.673192262649536
Epoch:  30 Loss value:  2.377135753631592
Epoch:  40 Loss value:  2.0668821334838867
Epoch:  50 Loss value:  1.8262720108032227
Epoch:  60 Loss value:  1.6366795301437378
Epoch:  70 Loss value:  1.4706857204437256
Epoch:  80 Loss value:  1.3549813032150269
Epoch:  90 Loss value:  1.2009940147399902
Epoch:  100 Loss value:  1.1459907293319702
Epoch:  110 Loss value:  1.0935158729553223
Epoch:  120 Loss value:  1.0327879190444946
Epoch:  130 Loss value:  0.962049126625061
Epoch:  140 Loss value:  0.9229065179824829
Epoch:  150 Loss value:  0.9002360701560974
Epoch:  160 Loss value:  0.8217368125915527
Epoch:  170 Loss value:  0.7926322221755981
Epoch:  180 Loss value:  0.7458497285842896
Epoch:  190 Loss value:  0.7337234020233154
Epoch:  200 Loss value:  0.6851602792739868
Epoch:  210 Loss value:  0.6345052719116211
Epoch:  220 Loss value:  0.6353235244750977
Epoc

# Data Scaling

In [38]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()

In [39]:
X_scaled = scaler.fit_transform(X_tensors)
X_scaled

array([[ 1.0687974 , -0.34455075, -0.1016875 , ...,  0.47266656,
         0.04330197,  1.81036042],
       [ 0.93332887,  0.14061552, -0.14118477, ...,  0.39705111,
         0.73487264,  2.24205783],
       [ 0.25598625,  0.04964684, -0.08193887, ...,  0.4869538 ,
         1.7715104 ,  2.92106578],
       ...,
       [ 1.82742114, -0.61745677, -0.35841972, ..., -0.19123529,
        -0.13812017,  1.27141778],
       [ 1.80032743, -0.64777967, -0.27942519, ..., -0.86951795,
         0.37390363,  0.43154519],
       [ 1.44810927, -1.07230015, -0.35841972, ..., -0.49802014,
         0.40109603,  0.68200519]], shape=(2200, 7))

In [40]:
X_scaled_tensors = torch.tensor(X_scaled, dtype=torch.float)

- Now we have scaled our data .
- Lets apply train_test_split

In [41]:
X_train, X_test, y_train, y_test = train_test_split(X_scaled_tensors, y_tensors, test_size=0.2, random_state=42)

In [42]:
model = CropRecommendationModelReLU()
optimizer = torch.optim.Adam(model.parameters(), lr=0.001)

In [43]:

run = wandb.init(
    # Set the wandb entity where your project will be logged (generally your team name).
    entity="aishwaryapatil845-aish-com",
    # Set the wandb project where this run will be logged.
    project="Crop_Recommendation",
    name="Model-epoch-500-scaled-data-new",
    # Track hyperparameters and run metadata.
    config={
        "learning_rate": 0.001,
        "architecture": "FNN",
        "dataset": "crop_recommndation",
        "epochs": 500,
    },
)

# Training loop 
epoches = 500

for epoch in range(epoches):
    model.train()

    out = model(X_train)
    loss = loss_function(out, y_train)

    optimizer.zero_grad()
    loss.backward()
    optimizer.step()

    # accuracy
    model.eval()
    y_pred = model(X_test).argmax(dim=1)
    acc = accuracy_score(y_test, y_pred)

    if epoch % 10 == 0 :
        print("Epoch: ", epoch, "Loss value: ", loss.item())
        run.log({"loss": loss.item(), "epoch": epoch, "accuracy": acc})

accuracy,▁▂▃▄▅▆▆▆▆▇▇▇▇▇▇▇▇███████████████████████
epoch,▁▁▁▁▂▂▂▂▂▂▃▃▃▃▃▄▄▄▄▄▄▅▅▅▅▅▅▆▆▆▆▆▆▇▇▇▇▇██
loss,█▇▆▆▅▄▄▃▃▃▃▂▂▂▂▂▂▂▂▂▂▁▂▂▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁
accuracy,0.93864
epoch,490
loss,0.3556


Epoch:  0 Loss value:  3.092421770095825
Epoch:  10 Loss value:  3.0738091468811035
Epoch:  20 Loss value:  3.0420870780944824
Epoch:  30 Loss value:  2.974956750869751
Epoch:  40 Loss value:  2.8483693599700928
Epoch:  50 Loss value:  2.6604607105255127
Epoch:  60 Loss value:  2.436279535293579
Epoch:  70 Loss value:  2.208395004272461
Epoch:  80 Loss value:  1.9824732542037964
Epoch:  90 Loss value:  1.7815877199172974
Epoch:  100 Loss value:  1.635197639465332
Epoch:  110 Loss value:  1.5291986465454102
Epoch:  120 Loss value:  1.3977710008621216
Epoch:  130 Loss value:  1.28412663936615
Epoch:  140 Loss value:  1.2241555452346802
Epoch:  150 Loss value:  1.112443447113037
Epoch:  160 Loss value:  1.02720308303833
Epoch:  170 Loss value:  0.9277424812316895
Epoch:  180 Loss value:  0.866072416305542
Epoch:  190 Loss value:  0.8120380640029907
Epoch:  200 Loss value:  0.771253228187561
Epoch:  210 Loss value:  0.7209464311599731
Epoch:  220 Loss value:  0.7218647599220276
Epoch:  230

## Increase hidden layer

In [44]:
X_train, X_test, y_train, y_test = train_test_split(X_scaled_tensors, y_tensors, test_size=0.2, random_state=42)

In [45]:
class CropRecommendationModelMoreNeurons(nn.Module):
    def __init__(self):
        super(CropRecommendationModelMoreNeurons, self).__init__()

        # layers
        self.fc1 = nn.Linear(7, 14)
        self.relu1 = nn.ReLU()
        
        # ------ hidden layer
        self.fc2 = nn.Linear(14, 28)
        self.relu2 = nn.ReLU()
        self.do1 = nn.Dropout(0.2)
        
        self.fc3 = nn.Linear(28, 56)
        self.relu3 = nn.ReLU()
        self.do2 = nn.Dropout(0.2)
        
        self.fc4 = nn.Linear(56, 112)
        self.relu4 = nn.ReLU()
        self.do3 = nn.Dropout(0.2)
        # -------
        self.fc5 = nn.Linear(112, 56) 
        self.relu5 = nn.ReLU()
        self.do4 = nn.Dropout(0.1)

        self.fc6 = nn.Linear(56, 34)
        self.relu6 = nn.ReLU()
        self.do5 = nn.Dropout(0.1)

        # ------
        self.fc7 = nn.Linear(34, 22) # output layer
        
    def forward(self, x):
        x = self.fc1(x) # input layer
        x = self.relu1(x)
        

        # hidden layer
        x = self.fc2(x)
        x = self.relu2(x)
        x = self.do1(x)
        
        x = self.fc3(x)
        x = self.relu3(x)
        x = self.do2(x)
        
        x = self.fc4(x)
        x = self.relu4(x)
        x = self.do3(x)

        x = self.fc5(x)
        x = self.relu5(x)
        x = self.do4(x)

        x = self.fc6(x)
        x = self.relu6(x)
        x = self.do5(x)

        x = self.fc7(x) # output layer

        return x

In [46]:
model = CropRecommendationModelMoreNeurons()
optimizer = torch.optim.Adam(model.parameters(), lr=0.001)

In [47]:

run = wandb.init(
    # Set the wandb entity where your project will be logged (generally your team name).
    entity="aishwaryapatil845-aish-com",
    # Set the wandb project where this run will be logged.
    project="Crop_Recommendation",
    name="Model-epoch-500-more-neurons",
    # Track hyperparameters and run metadata.
    config={
        "learning_rate": 0.001,
        "architecture": "FNN",
        "dataset": "crop_recommndation",
        "epochs": 500,
    },
)

# Training loop 
epoches = 500

for epoch in range(epoches):
    model.train()

    out = model(X_train)
    loss = loss_function(out, y_train)

    optimizer.zero_grad()
    loss.backward()
    optimizer.step()

    # accuracy
    model.eval()
    y_pred = model(X_test).argmax(dim=1)
    acc = accuracy_score(y_test, y_pred)

    if epoch % 10 == 0 :
        print("Epoch: ", epoch, "Loss value: ", loss.item())
        run.log({"loss": loss.item(), "epoch": epoch, "accuracy": acc})

accuracy,▁▁▂▂▂▃▄▅▅▆▆▇▇▇▇▇▇███████████████████████
epoch,▁▁▁▁▂▂▂▂▂▂▃▃▃▃▃▄▄▄▄▄▅▅▅▅▅▅▆▆▆▆▆▆▇▇▇▇▇███
loss,████▇▆▅▅▄▄▃▃▃▃▃▂▂▂▂▂▂▂▂▂▂▂▁▁▁▁▁▁▁▁▁▁▁▁▁▁
accuracy,0.94318
epoch,490
loss,0.30361


Epoch:  0 Loss value:  3.098057985305786
Epoch:  10 Loss value:  3.086609125137329
Epoch:  20 Loss value:  3.0460453033447266
Epoch:  30 Loss value:  2.9059667587280273
Epoch:  40 Loss value:  2.650160551071167
Epoch:  50 Loss value:  2.390608072280884
Epoch:  60 Loss value:  2.126918077468872
Epoch:  70 Loss value:  1.8408361673355103
Epoch:  80 Loss value:  1.6406961679458618
Epoch:  90 Loss value:  1.398672342300415
Epoch:  100 Loss value:  1.2572458982467651
Epoch:  110 Loss value:  1.1190067529678345
Epoch:  120 Loss value:  1.0295072793960571
Epoch:  130 Loss value:  0.9510139226913452
Epoch:  140 Loss value:  0.9158233404159546
Epoch:  150 Loss value:  0.8625760078430176
Epoch:  160 Loss value:  0.8264829516410828
Epoch:  170 Loss value:  0.7359643578529358
Epoch:  180 Loss value:  0.7268385887145996
Epoch:  190 Loss value:  0.6998481750488281
Epoch:  200 Loss value:  0.6633797287940979
Epoch:  210 Loss value:  0.6256534457206726
Epoch:  220 Loss value:  0.5862194299697876
Epoch

# Using different optimizer -SGD

In [49]:
model = CropRecommendationModelMoreNeurons()

optimizer = torch.optim.SGD(model.parameters(), lr=0.001, momentum=0.9)


In [50]:

run = wandb.init(
    # Set the wandb entity where your project will be logged (generally your team name).
    entity="aishwaryapatil845-aish-com",
    # Set the wandb project where this run will be logged.
    project="Crop_Recommendation",
    name="Model-epoch-500-SGD",
    # Track hyperparameters and run metadata.
    config={
        "learning_rate": 0.001,
        "momentum": 0.9,
        "architecture": "FNN",
        "dataset": "crop_recommndation",
        "epochs": 500,
    },
)

# Training loop 
epoches = 500

for epoch in range(epoches):
    model.train()

    out = model(X_train)
    loss = loss_function(out, y_train)

    optimizer.zero_grad()
    loss.backward()
    optimizer.step()

    # accuracy
    model.eval()
    y_pred = model(X_test).argmax(dim=1)
    acc = accuracy_score(y_test, y_pred)

    if epoch % 10 == 0 :
        print("Epoch: ", epoch, "Loss value: ", loss.item())
        run.log({"loss": loss.item(), "epoch": epoch, "accuracy": acc})

wandb: W&B API key is configured. Use `wandb login --relogin` to force relogin


accuracy,▁▁▁▁▁▄▄▅▅▆▆▆▆▆▇▇▇▇▇▇▇▇██████████████████
epoch,▁▁▁▁▂▂▂▂▂▂▃▃▃▃▃▄▄▄▄▄▅▅▅▅▅▆▆▆▆▆▆▇▇▇▇▇▇███
loss,███▇▆▅▄▄▃▃▃▃▃▂▂▂▂▂▂▂▂▂▂▂▂▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁
accuracy,0.94318
epoch,490
loss,0.25189


Epoch:  0 Loss value:  3.09574031829834
Epoch:  10 Loss value:  3.095754623413086
Epoch:  20 Loss value:  3.094839096069336
Epoch:  30 Loss value:  3.0953896045684814
Epoch:  40 Loss value:  3.0955963134765625
Epoch:  50 Loss value:  3.095043182373047
Epoch:  60 Loss value:  3.095336675643921
Epoch:  70 Loss value:  3.094695806503296
Epoch:  80 Loss value:  3.0952813625335693
Epoch:  90 Loss value:  3.0944674015045166
Epoch:  100 Loss value:  3.094524383544922
Epoch:  110 Loss value:  3.094365358352661
Epoch:  120 Loss value:  3.0949013233184814
Epoch:  130 Loss value:  3.0942022800445557
Epoch:  140 Loss value:  3.0949060916900635
Epoch:  150 Loss value:  3.0946500301361084
Epoch:  160 Loss value:  3.0943875312805176
Epoch:  170 Loss value:  3.093703508377075
Epoch:  180 Loss value:  3.094310998916626
Epoch:  190 Loss value:  3.0940537452697754
Epoch:  200 Loss value:  3.0940821170806885
Epoch:  210 Loss value:  3.0938727855682373
Epoch:  220 Loss value:  3.0940427780151367
Epoch:  23

# Saving Model
- The best model with the scaled data
- Lets save scaled model

In [51]:
model = CropRecommendationModelReLU()
optimizer = torch.optim.Adam(model.parameters(), lr=0.001)

In [52]:


# Training loop 
epoches = 501

for epoch in range(epoches):
    model.train()

    out = model(X_train)
    loss = loss_function(out, y_train)

    optimizer.zero_grad()
    loss.backward()
    optimizer.step()

    # accuracy
    model.eval()
    y_pred = model(X_test).argmax(dim=1)
    acc = accuracy_score(y_test, y_pred)

    if epoch % 10 == 0 :
        print("Epoch: ", epoch, " Loss value: ", loss.item(), " Accuracy: ", acc)
        

Epoch:  0  Loss value:  3.0956883430480957  Accuracy:  0.05909090909090909
Epoch:  10  Loss value:  3.075613021850586  Accuracy:  0.11136363636363636
Epoch:  20  Loss value:  3.0427277088165283  Accuracy:  0.11818181818181818
Epoch:  30  Loss value:  2.986079454421997  Accuracy:  0.15227272727272728
Epoch:  40  Loss value:  2.874899387359619  Accuracy:  0.18181818181818182
Epoch:  50  Loss value:  2.7138099670410156  Accuracy:  0.20454545454545456
Epoch:  60  Loss value:  2.5181477069854736  Accuracy:  0.24772727272727274
Epoch:  70  Loss value:  2.306511163711548  Accuracy:  0.3068181818181818
Epoch:  80  Loss value:  2.0623977184295654  Accuracy:  0.42727272727272725
Epoch:  90  Loss value:  1.8253499269485474  Accuracy:  0.4954545454545455
Epoch:  100  Loss value:  1.6318392753601074  Accuracy:  0.5522727272727272
Epoch:  110  Loss value:  1.4768187999725342  Accuracy:  0.6136363636363636
Epoch:  120  Loss value:  1.3357040882110596  Accuracy:  0.6772727272727272
Epoch:  130  Loss v

In [53]:
from sklearn.metrics import classification_report

In [55]:
X_test

tensor([[ 1.3668, -1.1026, -0.0227,  ...,  1.0444, -0.3676, -1.4042],
        [ 1.2855, -1.3755,  0.0563,  ...,  0.6757, -0.2716, -0.9834],
        [ 0.2289,  0.2619,  0.0168,  ...,  0.9825,  0.6100,  0.2059],
        ...,
        [ 1.9087, -0.1929, -0.6349,  ...,  0.3511,  1.6203, -0.5636],
        [ 1.7732, -0.0413, -0.5757,  ...,  0.1748, -0.4587, -0.6622],
        [-1.2342,  0.4438, -0.5559,  ..., -1.7240, -0.4495,  0.9447]])

In [54]:
y_pred = model(X_test).argmax(dim=1)
y_pred

tensor([15, 21, 17, 17,  0, 12,  0, 13, 14, 10,  2,  4, 19,  8,  4, 19,  0, 11,
        17, 15,  5, 17, 16, 17,  3,  8, 14, 16, 18, 20, 19, 10,  8, 10,  8,  2,
         8,  3,  3,  3, 17, 12,  2, 11, 14, 11, 18,  4, 15, 11,  2,  5,  7, 14,
         5,  9,  6,  0,  1, 10, 21,  4, 10, 16, 17,  2, 16, 20, 15, 18, 15,  4,
         8,  1,  2, 17,  1,  6, 21, 16,  5,  3,  8, 13, 16, 12,  5, 13,  2, 19,
        11, 13,  6, 17, 18,  9,  9,  5, 10, 10,  4, 20, 16, 15, 21,  9, 21,  1,
        18, 13,  1, 20, 11, 19, 18,  3, 11,  4, 19, 20, 18,  7,  2,  4,  3,  2,
         4, 11,  1, 13,  1,  9, 19,  3,  4, 16, 18,  1,  1,  0,  9, 15, 14, 13,
         4,  6,  0,  4,  9, 13, 14,  2, 21, 14, 18, 18, 18,  9, 11,  8,  3,  0,
        16,  6, 20,  4,  7, 10, 21,  7,  7,  2, 19,  3,  4, 11, 10,  7, 21,  8,
         5,  5,  9,  8, 13,  9,  1,  9,  4, 17, 17, 14, 12, 19, 21, 18, 11,  0,
         2,  3,  7,  7,  1,  6, 20, 19, 14,  1,  8, 14,  6,  3,  3,  3,  0, 20,
         9, 17,  5,  2,  9, 12, 12,  4, 

In [56]:
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        23
           1       1.00      1.00      1.00        21
           2       0.89      0.80      0.84        20
           3       0.96      1.00      0.98        26
           4       1.00      1.00      1.00        27
           5       1.00      0.94      0.97        17
           6       0.84      0.94      0.89        17
           7       1.00      1.00      1.00        14
           8       0.81      0.91      0.86        23
           9       0.86      0.90      0.88        20
          10       0.67      0.91      0.77        11
          11       0.95      0.86      0.90        21
          12       1.00      1.00      1.00        19
          13       1.00      0.92      0.96        24
          14       1.00      1.00      1.00        19
          15       1.00      1.00      1.00        17
          16       1.00      1.00      1.00        14
          17       0.96    

In [57]:
X.columns

Index(['N', 'P', 'K', 'temperature', 'humidity', 'ph', 'rainfall'], dtype='str')

In [58]:
import numpy as np

In [59]:
user_X = np.array([[100, 112, 130, 45, 100, 7, 100]])
user_X_tensors = torch.tensor(user_X, dtype=torch.float)

scaler.fit_transform(user_X_tensors)

array([[0., 0., 0., 0., 0., 0., 0.]])

In [61]:
model(user_X_tensors).argmax(dim=1)

tensor([0])

In [62]:
label_names[0]

'cotton'

- saving our model using safetensors

In [63]:
!uv add safetensors

Resolved 23 packages in 1.39s                                        
Prepared 1 package in 697ms                                              
Installed 1 package in 4ms                                  
 + safetensors==0.7.0


In [65]:
from safetensors.torch import save_file

In [66]:
model

CropRecommendationModelReLU(
  (fc1): Linear(in_features=7, out_features=14, bias=True)
  (relu1): ReLU()
  (fc2): Linear(in_features=14, out_features=28, bias=True)
  (relu2): ReLU()
  (do1): Dropout(p=0.2, inplace=False)
  (fc3): Linear(in_features=28, out_features=56, bias=True)
  (relu3): ReLU()
  (do2): Dropout(p=0.2, inplace=False)
  (fc4): Linear(in_features=56, out_features=34, bias=True)
  (relu4): ReLU()
  (do3): Dropout(p=0.1, inplace=False)
  (fc5): Linear(in_features=34, out_features=22, bias=True)
)

- print all layers weights and biases using `.state_dict()`

In [68]:
model.state_dict()

OrderedDict([('fc1.weight',
              tensor([[-0.2111,  0.2640,  0.1059,  0.3019, -0.5774,  0.0949, -0.3287],
                      [ 0.5342,  0.2489, -0.3143, -0.1934, -0.2043, -0.1657,  0.3539],
                      [-0.0987,  0.0512,  0.1112, -0.4442, -0.5137,  0.1988, -0.6578],
                      [ 0.3090,  0.3631,  0.1529,  0.0749,  0.7331,  0.0367,  0.1350],
                      [-0.0265,  0.5092,  0.0579, -0.3406,  0.4989, -0.1896,  0.5193],
                      [ 0.0211, -0.1412, -0.8118,  0.0179,  0.1731,  0.0084, -0.5765],
                      [ 0.2999,  0.4515,  0.4202,  0.3438,  0.0781,  0.0360,  0.1128],
                      [-0.4441,  0.3580,  0.0292, -0.0565, -0.4620, -0.2939,  0.1981],
                      [-0.1167,  0.7132,  0.0020,  0.1216,  0.2457, -0.0202, -0.1981],
                      [-0.1079, -0.6614,  0.0777,  0.0875,  0.2595, -0.3969, -0.4950],
                      [-0.5201,  0.3542, -0.5107,  0.0942,  0.7402,  0.0195,  0.0848],
               

In [69]:
tensors = model.state_dict()

In [70]:
save_file(tensors, "Models/crop_recommendation.safetensors")

### Load save safetensors models

- First load model architecture

In [75]:
class CropRecommendationModelLoad(nn.Module):
    def __init__(self):
        super(CropRecommendationModelLoad, self).__init__()

        # layers
        self.fc1 = nn.Linear(7, 14)
        self.relu1 = nn.ReLU()
        
        # ------ hidden layer
        self.fc2 = nn.Linear(14, 28)
        self.relu2 = nn.ReLU()
        self.do1 = nn.Dropout(0.2)
        
        self.fc3 = nn.Linear(28, 56)
        self.relu3 = nn.ReLU()
        self.do2 = nn.Dropout(0.2)
        
        self.fc4 = nn.Linear(56, 34)
        self.relu4 = nn.ReLU()
        self.do3 = nn.Dropout(0.1)
        # -------
        self.fc5 = nn.Linear(34, 22) # output layer

    def forward(self, x):
        x = self.fc1(x) # input layer
        x = self.relu1(x)
        

        # hidden layer
        x = self.fc2(x)
        x = self.relu2(x)
        x = self.do1(x)
        
        x = self.fc3(x)
        x = self.relu3(x)
        x = self.do2(x)
        
        x = self.fc4(x)
        x = self.relu4(x)
        x = self.do3(x)

        x = self.fc5(x) # output layer

        return x

In [76]:
loaded_model = CropRecommendationModelLoad()
loaded_model

CropRecommendationModelLoad(
  (fc1): Linear(in_features=7, out_features=14, bias=True)
  (relu1): ReLU()
  (fc2): Linear(in_features=14, out_features=28, bias=True)
  (relu2): ReLU()
  (do1): Dropout(p=0.2, inplace=False)
  (fc3): Linear(in_features=28, out_features=56, bias=True)
  (relu3): ReLU()
  (do2): Dropout(p=0.2, inplace=False)
  (fc4): Linear(in_features=56, out_features=34, bias=True)
  (relu4): ReLU()
  (do3): Dropout(p=0.1, inplace=False)
  (fc5): Linear(in_features=34, out_features=22, bias=True)
)

In [77]:
from safetensors.torch import load_file

In [78]:
tensors = load_file("Models/crop_recommendation.safetensors")
tensors

{'fc1.bias': tensor([ 0.4469,  0.2185, -0.3645,  0.0142,  0.1343, -0.1826,  0.3933,  0.1380,
          0.3635,  0.2131,  0.2194,  0.1017,  0.5438,  0.4990]),
 'fc1.weight': tensor([[-0.2111,  0.2640,  0.1059,  0.3019, -0.5774,  0.0949, -0.3287],
         [ 0.5342,  0.2489, -0.3143, -0.1934, -0.2043, -0.1657,  0.3539],
         [-0.0987,  0.0512,  0.1112, -0.4442, -0.5137,  0.1988, -0.6578],
         [ 0.3090,  0.3631,  0.1529,  0.0749,  0.7331,  0.0367,  0.1350],
         [-0.0265,  0.5092,  0.0579, -0.3406,  0.4989, -0.1896,  0.5193],
         [ 0.0211, -0.1412, -0.8118,  0.0179,  0.1731,  0.0084, -0.5765],
         [ 0.2999,  0.4515,  0.4202,  0.3438,  0.0781,  0.0360,  0.1128],
         [-0.4441,  0.3580,  0.0292, -0.0565, -0.4620, -0.2939,  0.1981],
         [-0.1167,  0.7132,  0.0020,  0.1216,  0.2457, -0.0202, -0.1981],
         [-0.1079, -0.6614,  0.0777,  0.0875,  0.2595, -0.3969, -0.4950],
         [-0.5201,  0.3542, -0.5107,  0.0942,  0.7402,  0.0195,  0.0848],
         [-0.1

In [79]:
loaded_model.load_state_dict(tensors)

<All keys matched successfully>

In [80]:
loaded_model.eval()

y_pred = loaded_model(X_test).argmax(dim=1)
acc = accuracy_score(y_test, y_pred)

In [81]:
acc

0.9477272727272728

In [82]:


# Training loop 
epoches = 101

for epoch in range(epoches):
    loaded_model.train()

    out = loaded_model(X_train)
    loss = loss_function(out, y_train)

    optimizer.zero_grad()
    loss.backward()
    optimizer.step()

    # accuracy
    loaded_model.eval()
    y_pred = loaded_model(X_test).argmax(dim=1)
    acc = accuracy_score(y_test, y_pred)

    if epoch % 10 == 0 :
        print("Epoch: ", epoch, " Loss value: ", loss.item(), " Accuracy: ", acc)
        

Epoch:  0  Loss value:  0.2816063165664673  Accuracy:  0.9477272727272728
Epoch:  10  Loss value:  0.27972960472106934  Accuracy:  0.9477272727272728
Epoch:  20  Loss value:  0.2761676013469696  Accuracy:  0.9477272727272728
Epoch:  30  Loss value:  0.272148996591568  Accuracy:  0.9477272727272728
Epoch:  40  Loss value:  0.2679167091846466  Accuracy:  0.9477272727272728
Epoch:  50  Loss value:  0.2637617588043213  Accuracy:  0.9477272727272728
Epoch:  60  Loss value:  0.24940131604671478  Accuracy:  0.9477272727272728
Epoch:  70  Loss value:  0.2827868163585663  Accuracy:  0.9477272727272728
Epoch:  80  Loss value:  0.2593800127506256  Accuracy:  0.9477272727272728
Epoch:  90  Loss value:  0.27890193462371826  Accuracy:  0.9477272727272728
Epoch:  100  Loss value:  0.28055354952812195  Accuracy:  0.9477272727272728


## Deploying model on hugging face

In [92]:
!uv add huggingface_hub

Resolved 39 packages in 2ms
Audited 37 packages in 0.53ms


In [93]:
!huggingface-cli login

/bin/bash: line 1: huggingface-cli: command not found


In [94]:
from huggingface_hub import login 

In [95]:
login()

In [101]:
from huggingface_hub import HfApi, create_repo

In [102]:
api = HfApi()

In [103]:
# create a repo for our model on hugging face
create_repo(repo_id="Aishwarya240/Crop_Recommendation_Model", repo_type="model", exist_ok=True)

RepoUrl('https://huggingface.co/Aishwarya240/Crop_Recommendation_Model', endpoint='https://huggingface.co', repo_type='model', repo_id='Aishwarya240/Crop_Recommendation_Model')

In [104]:
api.upload_file(
    path_or_fileobj="Models/crop_recommendation.safetensors",
    path_in_repo="crop_recommendation.safetensors",
    repo_id="Aishwarya240/Crop_Recommendation_Model",
    repo_type="model",
)

Processing Files (0 / 0): |          |  0.00B /  0.00B            

New Data Upload: |          |  0.00B /  0.00B            

CommitInfo(commit_url='https://huggingface.co/Aishwarya240/Crop_Recommendation_Model/commit/d054d8d20accc01e956e765a5ce6d63dfbafaca3', commit_message='Upload crop_recommendation.safetensors with huggingface_hub', commit_description='', oid='d054d8d20accc01e956e765a5ce6d63dfbafaca3', pr_url=None, repo_url=RepoUrl('https://huggingface.co/Aishwarya240/Crop_Recommendation_Model', endpoint='https://huggingface.co', repo_type='model', repo_id='Aishwarya240/Crop_Recommendation_Model'), pr_revision=None, pr_num=None)

## Using uploaded huggingface model

In [105]:
from huggingface_hub import hf_hub_download

In [106]:
file_path = hf_hub_download(repo_id="Sakib-Dalal/Crop_Recommendation_model", filename="crop_recommendation.safetensors")

crop_recommendation.safetensors:   0%|          | 0.00/20.2k [00:00<?, ?B/s]

In [107]:
file_path

'/home/aishwarya/.cache/huggingface/hub/models--Sakib-Dalal--Crop_Recommendation_model/snapshots/745702e83ffd74ff7e0d8335fff82b0f17bfaa01/crop_recommendation.safetensors'

In [108]:
from safetensors.torch import load_file

In [109]:
tensors = load_file(file_path)

In [110]:
tensors

{'fc1.bias': tensor([ 0.1682,  0.2715,  0.3995,  0.0408,  0.6122,  0.2638, -0.3094, -0.3033,
          0.4330,  0.0684, -0.0122, -0.0788,  0.6186,  0.5966]),
 'fc1.weight': tensor([[-0.4099,  0.1586, -0.1997, -0.0978,  0.5617, -0.1307,  0.5204],
         [-0.2615,  0.3210,  0.1499,  0.0720, -0.2259, -0.4872, -0.5836],
         [-0.3312,  0.1528, -0.8624, -0.0855, -0.1428, -0.0802, -0.2462],
         [-0.2278, -0.2462, -0.5358,  0.0399, -0.5327, -0.0098,  0.5400],
         [-0.1217, -0.1039,  0.4865, -0.1106,  0.5684, -0.1610, -0.1555],
         [-0.0585, -0.0673,  0.4725,  0.6143, -0.1365,  0.1546, -0.3258],
         [ 0.3914, -0.2846,  0.1439,  0.1654,  0.3906,  0.1638, -0.6746],
         [-0.2153, -0.2979, -0.5354, -0.0987,  0.2251, -0.0177,  0.0010],
         [-0.1484, -0.0718, -0.7016, -0.0033,  0.3152,  0.2956, -0.0331],
         [-0.2977, -0.6102, -0.0704,  0.2466, -0.0431, -0.4303, -0.0941],
         [ 0.5524, -0.3058, -0.0865, -0.0255, -0.1212,  0.1358, -0.0978],
         [-0.2

In [114]:
class CropRecommendationModelSakib(nn.Module):
    def __init__(self):
        super(CropRecommendationModelSakib, self).__init__()

        # layers
        self.fc1 = nn.Linear(7, 14)
        self.relu1 = nn.ReLU()
        
        # ------ hidden layer
        self.fc2 = nn.Linear(14, 28)
        self.relu2 = nn.ReLU()
        self.do1 = nn.Dropout(0.2)
        
        self.fc3 = nn.Linear(28, 56)
        self.relu3 = nn.ReLU()
        self.do2 = nn.Dropout(0.2)
        
        self.fc4 = nn.Linear(56, 34)
        self.relu4 = nn.ReLU()
        self.do3 = nn.Dropout(0.1)
        # -------
        self.fc5 = nn.Linear(34, 22) # output layer

    def forward(self, x):
        x = self.fc1(x) # input layer
        x = self.relu1(x)
        

        # hidden layer
        x = self.fc2(x)
        x = self.relu2(x)
        x = self.do1(x)
        
        x = self.fc3(x)
        x = self.relu3(x)
        x = self.do2(x)
        
        x = self.fc4(x)
        x = self.relu4(x)
        x = self.do3(x)

        x = self.fc5(x) # output layer

        return x

In [115]:
model = CropRecommendationModelSakib()
model

CropRecommendationModelSakib(
  (fc1): Linear(in_features=7, out_features=14, bias=True)
  (relu1): ReLU()
  (fc2): Linear(in_features=14, out_features=28, bias=True)
  (relu2): ReLU()
  (do1): Dropout(p=0.2, inplace=False)
  (fc3): Linear(in_features=28, out_features=56, bias=True)
  (relu3): ReLU()
  (do2): Dropout(p=0.2, inplace=False)
  (fc4): Linear(in_features=56, out_features=34, bias=True)
  (relu4): ReLU()
  (do3): Dropout(p=0.1, inplace=False)
  (fc5): Linear(in_features=34, out_features=22, bias=True)
)

In [116]:
model.load_state_dict(tensors)

<All keys matched successfully>

In [117]:
y_pred = model(X_test).argmax(dim=1)
acc= accuracy_score(y_test, y_pred)

In [118]:
acc

0.8818181818181818

- Lets retrain sakib model

In [121]:
optimizer = torch.optim.Adam(model.parameters(), lr=0.001)
loss_function = nn.CrossEntropyLoss()

In [122]:

# Training loop 
epoches = 101

for epoch in range(epoches):
    model.train()

    out = loaded_model(X_train)
    loss = loss_function(out, y_train)

    optimizer.zero_grad()
    loss.backward()
    optimizer.step()

    # accuracy
    model.eval()
    y_pred = model(X_test).argmax(dim=1)
    acc = accuracy_score(y_test, y_pred)

    if epoch % 10 == 0 :
        print("Epoch: ", epoch, " Loss value: ", loss.item(), " Accuracy: ", acc)
        

Epoch:  0  Loss value:  0.08622344583272934  Accuracy:  0.9613636363636363
Epoch:  10  Loss value:  0.08622344583272934  Accuracy:  0.9613636363636363
Epoch:  20  Loss value:  0.08622344583272934  Accuracy:  0.9613636363636363
Epoch:  30  Loss value:  0.08622344583272934  Accuracy:  0.9613636363636363
Epoch:  40  Loss value:  0.08622344583272934  Accuracy:  0.9613636363636363
Epoch:  50  Loss value:  0.08622344583272934  Accuracy:  0.9613636363636363
Epoch:  60  Loss value:  0.08622344583272934  Accuracy:  0.9613636363636363
Epoch:  70  Loss value:  0.08622344583272934  Accuracy:  0.9613636363636363
Epoch:  80  Loss value:  0.08622344583272934  Accuracy:  0.9613636363636363
Epoch:  90  Loss value:  0.08622344583272934  Accuracy:  0.9613636363636363
Epoch:  100  Loss value:  0.08622344583272934  Accuracy:  0.9613636363636363


In [123]:
y_pred = model(X_test).argmax(dim=1)
acc = accuracy_score(y_test, y_pred)

In [124]:
acc

0.9613636363636363