# PyTorch Tensors
<a href="https://docs.pytorch.org/docs/stable/generated/torch.Tensor.ndim.html">Pytorch Tensors Documentation</a>

In [2]:
import torch

In [3]:
torch.__version__

'2.10.0+cu128'

Create a custom tensor using pytorch

In [7]:
n = torch.tensor(5)

In [8]:
n

tensor(5)

This will check dimensions of the tensor `n`.

In [9]:
n.ndim

0

Using python list as tensor

In [11]:
l = [1, 2, 3]
v = torch.tensor(l)

In [12]:
v

tensor([1, 2, 3])

In [13]:
type(l), type(v)

(list, torch.Tensor)

In [16]:
v.ndim

1

Using numpy array as tensor

In [15]:
import numpy as np

In [17]:
a = np.array([1, 2, 3, 4, 5])

In [18]:
a

array([1, 2, 3, 4, 5])

In [19]:
type(a)

numpy.ndarray

In [20]:
t = torch.tensor(a)

In [21]:
t

tensor([1, 2, 3, 4, 5])

In [22]:
type(t)

torch.Tensor

In [23]:
d = np.array([[1, 2, 3], [4, 5, 6]])

In [24]:
d

array([[1, 2, 3],
       [4, 5, 6]])

In [25]:
d.ndim

2

In [26]:
t = torch.tensor(d)

In [27]:
t

tensor([[1, 2, 3],
        [4, 5, 6]])

Numpy random array to tensor

In [43]:
X = np.random.rand(100)

In [44]:
X

array([0.68425469, 0.37421605, 0.29192519, 0.75595315, 0.32348506,
       0.58968236, 0.46027025, 0.8995534 , 0.89978193, 0.44014577,
       0.0506419 , 0.1165165 , 0.53192973, 0.52086235, 0.00955546,
       0.2531712 , 0.99084441, 0.89255888, 0.97657072, 0.98027378,
       0.45127986, 0.40218999, 0.02528643, 0.40694083, 0.43099116,
       0.70050249, 0.18832912, 0.84791841, 0.8960438 , 0.83759582,
       0.48496554, 0.89695659, 0.74069428, 0.25671022, 0.5232985 ,
       0.71404793, 0.52589707, 0.19862486, 0.07676023, 0.18936727,
       0.8495179 , 0.48535094, 0.68096214, 0.60820867, 0.78288055,
       0.96517085, 0.41437523, 0.20448242, 0.77840936, 0.33546594,
       0.38066179, 0.94929707, 0.68484476, 0.05233301, 0.84014603,
       0.09066777, 0.82122411, 0.9495468 , 0.45021232, 0.05634139,
       0.13331647, 0.85943392, 0.48305933, 0.41634293, 0.78189989,
       0.29796074, 0.29643535, 0.28980222, 0.8786428 , 0.59276145,
       0.03447299, 0.86364324, 0.51899667, 0.7099802 , 0.54760

In [45]:
X.ndim

1

In [46]:
X_tensors = torch.tensor(X)
X_tensors

tensor([0.6843, 0.3742, 0.2919, 0.7560, 0.3235, 0.5897, 0.4603, 0.8996, 0.8998,
        0.4401, 0.0506, 0.1165, 0.5319, 0.5209, 0.0096, 0.2532, 0.9908, 0.8926,
        0.9766, 0.9803, 0.4513, 0.4022, 0.0253, 0.4069, 0.4310, 0.7005, 0.1883,
        0.8479, 0.8960, 0.8376, 0.4850, 0.8970, 0.7407, 0.2567, 0.5233, 0.7140,
        0.5259, 0.1986, 0.0768, 0.1894, 0.8495, 0.4854, 0.6810, 0.6082, 0.7829,
        0.9652, 0.4144, 0.2045, 0.7784, 0.3355, 0.3807, 0.9493, 0.6848, 0.0523,
        0.8401, 0.0907, 0.8212, 0.9495, 0.4502, 0.0563, 0.1333, 0.8594, 0.4831,
        0.4163, 0.7819, 0.2980, 0.2964, 0.2898, 0.8786, 0.5928, 0.0345, 0.8636,
        0.5190, 0.7100, 0.5476, 0.3665, 0.2994, 0.3883, 0.5101, 0.9815, 0.1082,
        0.7837, 0.6479, 0.7986, 0.7570, 0.5594, 0.3606, 0.1374, 0.0037, 0.8270,
        0.3683, 0.1821, 0.9993, 0.2018, 0.1100, 0.9267, 0.7277, 0.2261, 0.7847,
        0.5552], dtype=torch.float64)

Zero tensor array 

In [47]:
torch.zeros(10)

tensor([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [48]:
torch.zeros([3, 10])

tensor([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

One tensor array

In [50]:
torch.ones(10)

tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [52]:
torch.ones([3, 10])

tensor([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

Getting tensor items using index

In [53]:
g = torch.tensor([1, 2, 3, 4, 5])

In [54]:
g

tensor([1, 2, 3, 4, 5])

In [55]:
g[0]

tensor(1)

In [56]:
g[4]

tensor(5)

In [57]:
g[1:4]

tensor([2, 3, 4])

In [58]:
d = torch.tensor([[1, 2, 3], [4, 5, 6]])

In [59]:
d

tensor([[1, 2, 3],
        [4, 5, 6]])

In [60]:
d.ndim

2

In [61]:
d[1][1]

tensor(5)

In [62]:
d[0][2]

tensor(3)

In [66]:
d[0][1:3]

tensor([2, 3])

In [67]:
# Float 64 data types tensors
torch.tensor([1, 2, 3], dtype=torch.float64)

tensor([1., 2., 3.], dtype=torch.float64)

In [68]:
# Int 32 data type tensors
torch.tensor([2.3456, 4.6789, 2.4678], dtype=torch.int32)

tensor([2, 4, 2], dtype=torch.int32)

In [70]:
# Float 32 data type tensors 
X = torch.tensor([2.3892, 3.7986, 4.02853], dtype=torch.float32)

In [71]:
X

tensor([2.3892, 3.7986, 4.0285])

In [72]:
X.dtype

torch.float32

Create a tensor on dedicated device
- CPU
- NVIDIA GPU (CUDA)
- MAC GPU (MPS)

In [74]:
torch.tensor([1, 2, 3], device=torch.device("cpu"))

tensor([1, 2, 3])

In [75]:
torch.tensor([1, 2, 3], device=torch.device("cuda"))

tensor([1, 2, 3], device='cuda:0')

In [76]:
d = torch.tensor([1, 2, 3, 4, 5], device=torch.device("cuda"))
d

tensor([1, 2, 3, 4, 5], device='cuda:0')

In [77]:
d.device

device(type='cuda', index=0)

In [80]:
c = torch.tensor([1, 2, 3], dtype=torch.float64, device=torch.device("cuda"))
c

tensor([1., 2., 3.], device='cuda:0', dtype=torch.float64)

Generating random tensors

In [81]:
n = torch.rand(10)

In [82]:
n 

tensor([6.7696e-01, 3.2057e-01, 7.6204e-01, 9.4420e-01, 1.2909e-01, 7.0983e-02,
        2.1866e-01, 7.6056e-04, 2.6326e-01, 6.8488e-02])

In [85]:
n = torch.rand(10, 2,  dtype=torch.float, device=torch.device("cuda"))
n

tensor([[0.7967, 0.3068],
        [0.5841, 0.9651],
        [0.4290, 0.7308],
        [0.8421, 0.7819],
        [0.9935, 0.7329],
        [0.8487, 0.3684],
        [0.1692, 0.7707],
        [0.1273, 0.8073],
        [0.3045, 0.0438],
        [0.5909, 0.4791]], device='cuda:0')

In [87]:
n = torch.randint(1, 10, size=(10,), device=torch.device("cuda"))
n

tensor([4, 1, 5, 6, 6, 3, 2, 7, 7, 6], device='cuda:0')

In [88]:
n = torch.tensor([1, 2, 3, 4, 5], device=torch.device("cuda"))
n.to(torch.float32)

tensor([1., 2., 3., 4., 5.], device='cuda:0')

Tensor Operations

In [89]:
a = torch.tensor([1, 2, 3, 4, 5],device=torch.device("cuda"))
a

tensor([1, 2, 3, 4, 5], device='cuda:0')

In [91]:
torch.sum(a).to(device=torch.device("cuda"), dtype=torch.int64)

tensor(15, device='cuda:0')

In [92]:
a = torch.tensor([1, 2, 3, 4, 5], device=torch.device("cuda"))
b = torch.tensor([1, 2, 3, 4, 5], device=torch.device("cuda"))

torch.sub(a, b).to(device=torch.device("cuda"))

tensor([0, 0, 0, 0, 0], device='cuda:0')

In [94]:
# Multiplication
torch.mul(a, b).to(device=torch.device("cuda"))

tensor([ 1,  4,  9, 16, 25], device='cuda:0')

In [96]:
a = torch.rand(3, device=torch.device("cuda"))
b = torch.rand(3, device=torch.device("cuda"))



In [97]:
torch.mul(a, b).to(device=torch.device("cuda"))

tensor([0.0142, 0.7032, 0.2399], device='cuda:0')

### Comparison of CPU and GPU

In [113]:
a = torch.rand(100000000, device=torch.device("cuda"))

In [114]:
a

tensor([0.6947, 0.0694, 0.5418,  ..., 0.1933, 0.8438, 0.9051], device='cuda:0')

In [115]:
a.shape

torch.Size([100000000])

In [116]:
import time

In [117]:
s = time.time()
a.mul(a).to(device=torch.device("cpu"))
e = time.time() - s

print("CPU execution time: ", e)

CPU execution time:  0.28485107421875


In [118]:
s = time.time()
a.mul(a).to(device=torch.device("cuda"))
e = time.time() - s

print("GPU execution time: ", e)

GPU execution time:  0.0014545917510986328


 Tensor mean


In [119]:
a = torch.rand(3)
torch.mean(a)

tensor(0.2823)