# Token Embedding
- Convert unstructured test data into structured numerical data.
  

In [26]:
!uv pip install transformers

Audited 1 package in 4ms


In [27]:
import torch

In [28]:
from transformers import BertTokenizer, BertModel

- There are two parts in transformers
    - Tokenizer
    - Encoder Model

In [29]:
tokenizer = BertTokenizer.from_pretrained('bert-base-uncased')
model = BertModel.from_pretrained('bert-base-uncased')

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

BertModel LOAD REPORT from: bert-base-uncased
Key                                        | Status     |  | 
-------------------------------------------+------------+--+-
cls.predictions.transform.LayerNorm.bias   | UNEXPECTED |  | 
cls.predictions.transform.LayerNorm.weight | UNEXPECTED |  | 
cls.predictions.transform.dense.bias       | UNEXPECTED |  | 
cls.predictions.transform.dense.weight     | UNEXPECTED |  | 
cls.seq_relationship.weight                | UNEXPECTED |  | 
cls.predictions.bias                       | UNEXPECTED |  | 
cls.seq_relationship.bias                  | UNEXPECTED |  | 

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.


In [30]:
text = "Hello world apple is a fruit"

In [31]:
tokenizer(text)

{'input_ids': [101, 7592, 2088, 6207, 2003, 1037, 5909, 102], 'token_type_ids': [0, 0, 0, 0, 0, 0, 0, 0], 'attention_mask': [1, 1, 1, 1, 1, 1, 1, 1]}

In [32]:
sentence = ["This is a mat!", "My cat sits on the mat", "She sleeps on the mat"]

In [43]:
tokenizer(sentence)["input_ids"]

[[101, 2023, 2003, 1037, 13523, 999, 102],
 [101, 2026, 4937, 7719, 2006, 1996, 13523, 102],
 [101, 2016, 25126, 2006, 1996, 13523, 102]]

In [44]:
tokenize_text = tokenizer(text)

In [39]:
tokenize_text

{'input_ids': [101, 7592, 2088, 6207, 2003, 1037, 5909, 102], 'token_type_ids': [0, 0, 0, 0, 0, 0, 0, 0], 'attention_mask': [1, 1, 1, 1, 1, 1, 1, 1]}

In [40]:
tokenize_text["input_ids"]

[101, 7592, 2088, 6207, 2003, 1037, 5909, 102]

In [45]:
tokenize_text = tokenizer(text, return_tensors='pt', padding=True, truncation=True, max_length=128)
tokenize_text["input_ids"]

tensor([[ 101, 7592, 2088, 6207, 2003, 1037, 5909,  102]])

In [46]:
type(tokenize_text["input_ids"])

torch.Tensor

In [47]:
model(**tokenize_text)

BaseModelOutputWithPoolingAndCrossAttentions(last_hidden_state=tensor([[[-0.2703, -0.0570, -0.1508,  ...,  0.0264,  0.3211,  0.5075],
         [-0.6078,  0.3619,  0.8418,  ...,  0.3699,  0.6960,  0.2652],
         [-0.6297,  0.3657,  1.1717,  ...,  0.1686,  0.1669,  0.2557],
         ...,
         [-0.4788,  0.2052,  0.0516,  ...,  0.1702,  0.0424,  0.6111],
         [-0.1851,  0.5140, -0.4709,  ...,  0.2270, -0.0377, -0.8687],
         [ 0.6745,  0.1126, -0.4412,  ...,  0.4908, -0.5692, -0.3703]]],
       grad_fn=<NativeLayerNormBackward0>), pooler_output=tensor([[-9.2481e-01, -2.0625e-01, -4.8881e-02,  8.0025e-01,  4.0742e-01,
         -1.8229e-01,  8.5889e-01,  2.4806e-01,  1.1154e-01, -9.9999e-01,
          1.1472e-02,  5.9679e-01,  9.8660e-01, -4.7013e-01,  9.4279e-01,
         -6.9165e-01, -2.2963e-02, -5.5303e-01,  3.2637e-01, -4.6073e-01,
          6.0028e-01,  9.9634e-01,  5.5980e-01,  2.8031e-01,  3.7020e-01,
          6.6528e-01, -6.9237e-01,  9.3658e-01,  9.6193e-01,  7.314

- Our encoding model expects input in PyTorch tensors.

In [48]:
text = ["Hello world apple is a cat", "how are you?"]

In [49]:
tokenized_text = tokenizer(text, return_tensors='pt', padding=True, truncation=True, max_length=128)
tokenized_text["input_ids"]

tensor([[ 101, 7592, 2088, 6207, 2003, 1037, 4937,  102],
        [ 101, 2129, 2024, 2017, 1029,  102,    0,    0]])

In [50]:
tokenized_text


{'input_ids': tensor([[ 101, 7592, 2088, 6207, 2003, 1037, 4937,  102],
        [ 101, 2129, 2024, 2017, 1029,  102,    0,    0]]), 'token_type_ids': tensor([[0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0]]), 'attention_mask': tensor([[1, 1, 1, 1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1, 1, 0, 0]])}

In [51]:
type(tokenized_text["input_ids"])

torch.Tensor

In [57]:
# **tokenized_text for token encoding
model(**tokenized_text).keys()

odict_keys(['last_hidden_state', 'pooler_output'])

In [53]:
with torch.no_grad():
    out = model(**tokenized_text)

out["last_hidden_state"]

tensor([[[-0.2419,  0.0880, -0.0151,  ..., -0.2777,  0.2302,  0.4209],
         [-0.4994,  0.6492,  1.0223,  ..., -0.2836,  0.7439,  0.4839],
         [-0.7749,  0.8752,  1.1876,  ..., -0.5100,  0.2730,  0.3467],
         ...,
         [-0.3994,  0.4876,  0.4540,  ..., -0.4447,  0.3069,  1.0735],
         [-0.5459,  0.1270,  0.2667,  ..., -0.2422,  0.4461,  0.9208],
         [ 0.5536,  0.2056, -0.4421,  ...,  0.4332, -0.5706, -0.2373]],

        [[-0.0573,  0.1625, -0.4028,  ..., -0.4454,  0.2880,  0.3058],
         [-0.1744, -0.4683, -0.2665,  ..., -0.2229,  0.7547, -0.4456],
         [ 0.3816, -0.6513,  0.3829,  ..., -0.7145,  0.1510, -0.7006],
         ...,
         [ 0.6713, -0.0606, -0.2756,  ...,  0.1626, -0.3610, -0.2107],
         [ 0.0941,  0.0245,  0.3573,  ..., -0.0056,  0.2437, -0.2700],
         [-0.0835, -0.0276,  0.1523,  ...,  0.3175,  0.1654, -0.2160]]])

In [54]:
out["last_hidden_state"].shape

torch.Size([2, 8, 768])

In [55]:
new_out = out["last_hidden_state"][:, 0, :]
new_out

tensor([[-0.2419,  0.0880, -0.0151,  ..., -0.2777,  0.2302,  0.4209],
        [-0.0573,  0.1625, -0.4028,  ..., -0.4454,  0.2880,  0.3058]])

In [56]:
new_out.shape

torch.Size([2, 768])